// script generated by Xtreeme SiteXpert
// sitemap and search engine creator
// http://www.xtreeme.com/sitexpert
// Copyright(C) 2001-2002 Xtreeme GmbH

if (!document.loadHandlers)
{
	document.loadHandlers=new Array();
	document.loadHandlers[0]='initializeMenu';
	document.lastLoadHandler=0;
}
else
{
	document.lastLoadHandler++;
	document.loadHandlers[document.lastLoadHandler]='initializeMenu';
}
window.onload=initializeAll;
function errorTrap(){return true;}
window.onerror=errorTrap;

var nmenu;var nmn;for(nmn=1;nmn<=lastm;nmn++){nmenu=eval('window.m'+nmn);if(nmenu)break;}
iconTag="<IMG SRC=\'";
if (nmenu.imgFolder.indexOf('/')!=0)iconTag+=absPath;
iconTag+=nmenu.imgFolder+"/sxicona.gif\' BORDER=0 WIDTH="+nmenu.iconSize+" HEIGHT="+nmenu.iconSize+" HSPACE=6 ALIGN=RIGHT>";

var resizeRef=(nmenu.sepFrame&&!nmenu.openSameFrame)?parent:window;
var startWidth=resizeRef.innerWidth;
var startHeight=resizeRef.innerHeight;
resizeRef.onresize=function()
{
	if(resizeRef.innerWidth==startWidth && resizeRef.innerHeight==startHeight)return;
	resizeRef.location.reload();
}

function createMenuItem(nmenu,popup,itemLink,itemText,popupArray,levelAttribs,bLast,popupHeight)
{
    var itemWnd;
	eval("itemWnd=new Layer(nmenu.popupWidth,popup)");

	var itemHoverText="<font style='font-size:"+levelAttribs[0]+";width:"+(nmenu.popupWidth-nmenu.vertSpace*2-nmenu.bord*2)+"' color="+levelAttribs[5]+" face='"+levelAttribs[6]+"'>"+itemText+"</font>";
	var targetFr="";
	if (itemLink)
	{
		var startPos=itemText.indexOf('<!--');
		if(nmenu.sepFrame&&nmenu.openSameFrame)targetFr="target='"+nmenu.cntFrame+"'";
		if (startPos!=-1)
		{
			var endPos = itemText.indexOf('-->',startPos);
			targetFr = "target='"+itemText.substring (startPos+4,endPos)+"'";
		}
	}
	if(itemLink)itemHoverText="<a href=\""+itemLink+"\" "+targetFr+" style='width:"+(nmenu.popupWidth-nmenu.vertSpace*2-nmenu.bord*2)+";text-decoration:none'>"+itemHoverText+"</a>";
	if(levelAttribs[1])itemHoverText=itemHoverText.bold();
	if(levelAttribs[2])itemHoverText=itemHoverText.italic();
    if(popupArray)itemHoverText=iconTag+itemHoverText;

	itemText="<font style='font-size:"+levelAttribs[0]+";width:"+(nmenu.popupWidth-nmenu.vertSpace*2-nmenu.bord*2)+"' color="+levelAttribs[3]+" face='"+levelAttribs[6]+"'>"+itemText+"</font>";
    if(itemLink)itemText="<a href=\""+itemLink+"\" "+targetFr+" style='width:"+(nmenu.popupWidth-nmenu.vertSpace*2-nmenu.bord*2)+";text-decoration:none'>"+itemText+"</a>";
	if(levelAttribs[1])itemText=itemText.bold();
	if(levelAttribs[2])itemText=itemText.italic();
    if(popupArray)itemText=iconTag+itemText;

	itemWnd.captureEvents(Event.CLICK);
    itemWnd.onclick=onItemClick;
	addEvent(itemWnd,"mouseout",onItemOut,false);
	addEvent(itemWnd,"mouseover",onItemOver,false);
    itemWnd.document.write(itemText);
    itemWnd.document.close();
	itemWnd.document.tags.A.textDecoration="none";
	itemWnd.document.tags.FONT.width=nmenu.popupWidth-nmenu.vertSpace*2-nmenu.bord*2;
	itemWnd.document.tags.FONT.fontSize=levelAttribs[0];
	itemWnd.pageX=nmenu.vertSpace+nmenu.bord;
    if (popupArray)itemWnd.popupArray=popupArray;
    itemWnd.owner=popup;
	if(itemLink&&itemLink.indexOf(':/')==-1&&itemLink.indexOf(':\\')==-1&&itemLink.indexOf('/')!=0)itemWnd.url=unescape(absPath)+itemLink;
	else itemWnd.url=itemLink;
    itemWnd.pageY=popupHeight+nmenu.vertSpace;
    itemWnd.dispText=itemText;
	itemWnd.dispHoverText=itemHoverText;
    itemWnd.bgColor=levelAttribs[4];
    itemWnd.clip.top=-nmenu.vertSpace;
    itemWnd.clip.left=-nmenu.vertSpace;
    var newHeight=itemWnd.document.height+2*nmenu.vertSpace;
    itemWnd.resizeTo(nmenu.popupWidth-2*nmenu.bord,newHeight);
    itemWnd.visibility="inherit";
    return newHeight;
}

function createPopupFromCode(nmenu,arrayName,level)
{
	var popupName=arrayName+"popup";
	var popup=eval("nmenu.popupFrame.document."+popupName);
	if (popup)return popup;
	var levelAttribs;
	var nm=nmenu;
	if (level > nmenu.maxlev) {levelAttribs = eval ("nm.lev" + nmenu.maxlev) ;} else {levelAttribs = eval ("nm.lev" + level) ;}
	eval("nmenu.popupFrame.document."+popupName+"=new Layer(nmenu.popupWidth,nmenu.popupFrame)");
	popup=eval("nmenu.popupFrame.document."+popupName);
	popup.level=level;
    popup.wid=popupName;
	popup.highlightColor=levelAttribs[5];
	popup.normalColor=levelAttribs[3];
	popup.highlightBgColor=levelAttribs[7];
	popup.normalBgColor=levelAttribs[4];
	popup.zIndex=maxZ;
	popup.bgColor=nmenu.bord?nmenu.borderCol:levelAttribs[4];
	popup.nmenu=nmenu;
	addEvent(popup,"mouseout",onPopupOut,false);
	addEvent(popup,"mouseover",onPopupOver,false);
	var popupHeight=nmenu.bord;
	var array=eval(arrayName);
	var arrayItem;
	var popupText="";
	for(arrayItem=0;arrayItem<array.length/3;arrayItem++)
	{
		var popupArray=(array[arrayItem*3+2])?(arrayName+"_"+parseInt(arrayItem+1)):null;
		popupHeight+=createMenuItem(nmenu,popup,array[arrayItem*3+1],array[arrayItem*3],popupArray,levelAttribs,(arrayItem == array.length/3-1),popupHeight);
        popupHeight+=nmenu.sep;
	}
	popupHeight+=nmenu.bord;
    popup.resizeTo(nmenu.popupWidth,popupHeight);
	popup.popupHeight=popupHeight;
	return popup;
}

function closePopup(nmenu,popupId)
{
	if(popupId.indexOf('_')==-1){var hideWnd=eval("nmenu.popupFrame.document.HideItem");if(hideWnd)hideWnd.visibility='show';}
	var popup=eval("nmenu.popupFrame.document."+popupId);
	if (popup)
	{
		if (popup.expandedWnd) closePopup (nmenu,popup.expandedWnd.wid);
		popup.visibility="hide";
	}
	if (nmenu.activePopup && nmenu.activePopup.wid==popupId) nmenu.activePopup=null;
}

function absToRel(rect,refx,refy)
{
	var retval=new rct(rect.left-refx,rect.top-refy,rect.right-refx,rect.bottom-refy);
	return retval;
}

function openPopup(nmenu,popup,x,y,bDontMove)
{
	if(popup.wid.indexOf('_')==-1){var hideWnd=eval("nmenu.popupFrame.document.HideItem");if(hideWnd)hideWnd.visibility='hide';}
	popup.left=x;
	popup.top=y;
	popup.visibility="show";
	var browserRect=getBrowserRect(nmenu.popupFrame);
	if(x+nmenu.popupWidth>browserRect.right)popup.left=Math.max(0,browserRect.right-nmenu.popupWidth-5-popup.level*20);
	if(y+popup.popupHeight>browserRect.bottom)popup.top=Math.max(0,browserRect.bottom-popup.popupHeight-5);
}

function isChildOfActivePopup(nmenu,popup)
{
	var wnd=nmenu.activePopup;
	while(wnd)
	{
		if (wnd.wid==popup.wid)
			return true;
		wnd=wnd.expandedWnd;
	}
	return false;
}

function onPopupOver()
{
	var nmenu=this.nmenu;
	if (nmenu.activePopup && isChildOfActivePopup (nmenu,this)) clearTimeout(nmenu.activePopupTimeout);
}

function onPopupOut()
{
	var nmenu=this.nmenu;
	onPopupOutImpl(nmenu,this);
}

function onPopupOutImpl(nmenu,popup)
{
	if (nmenu.mout && nmenu.activePopup && isChildOfActivePopup (nmenu,popup))
	{
		if (nmenu.activePopupTimeout) clearTimeout (nmenu.activePopupTimeout);
		nmenu.activePopupTimeout=setTimeout("closePopup("+nmenu.name+",'"+nmenu.activePopup.wid+"');", nmenu.closeDelay);
	}
}

function rct(left,top,right,bottom)
{
	this.left=left;
	this.top=top;
	this.right=right;
	this.bottom=bottom;
}

function getBrowserRect(doc)
{
	var left=doc.pageXOffset;
	var top=doc.pageYOffset;
	var right=left+doc.innerWidth;
	var bottom=top+doc.innerHeight;
	var retval=new rct(left,top,right,bottom);
	return retval;	
}

function getClientRect(wnd)
{
	var left=wnd.pageX;
	var top=wnd.pageY;
	var right=left+wnd.document.width;
	var bottom=top+wnd.document.height;
	var retval=new rct(left,top,right,bottom);
	return retval;
}

function onItemClick()
{
	var item=this;
	var nmenu=this.owner.nmenu;
	if (item.url)
	{
		var startPos=item.dispText.indexOf('<!--');
		if (startPos!=-1)
		{
			var endPos = item.dispText.indexOf('-->',startPos);
			var trgFrame = item.dispText.substring (startPos+4,endPos);
			if (trgFrame=="_blank") window.open (item.url);
			else if (trgFrame.indexOf('_')==0) parent.location.href=item.url;
			else eval("parent.frames."+trgFrame).location.href=item.url;
		}
		else
		{
			var find=item.url.indexOf("javascript:");
			if (find!=-1)
				eval(item.url.substring(find));
			else
			{
				var mt=item.url.indexOf("mailto:");
				if(mt!=-1)window.location=item.url.substring(mt);
				else nmenu.targetFrame.location=item.url;
			}
		}
		if(nmenu.activePopup)closePopup(nmenu,nmenu.activePopup.id);
	}
    return false;
}

function onItemOver()
{
	var item=this;
	var nmenu=this.owner.nmenu;
	if (item.owner.expandedWnd)
	{
		closePopup(nmenu,item.owner.expandedWnd.wid);
	}
	if (item.url&&item.url.indexOf("javascript:")==-1)
		window.status=item.url;
	else
		window.status="";
	item.bgColor=item.owner.highlightBgColor;
	if(mswnd)
	{
		item.document.write(item.dispHoverText);
		item.document.close();
	}
	if (item.popupArray)
	{
		var rect=getClientRect(item);
		var x=item.pageX+nmenu.popupWidth-nmenu.levelOffset;//right-nmenu.levelOffset;
		var y=rect.top;
		var popup=createPopupFromCode(nmenu,item.popupArray,item.owner.level+1);
		item.owner.expandedWnd=popup;
		openPopup(nmenu,popup,x,y,false);
	}
}

function onItemOut()
{
	var item=this;
	var nmenu=this.owner.nmenu;
	if(mswnd)
	{
		item.document.write(item.dispText);
		item.document.close();
	}
	item.color=item.owner.normalColor;
	item.bgColor=item.owner.normalBgColor;
}

function expandMenu(nmenu,popupId,refWnd,e,ml,mt,mr,mb)
{
	if(!docLoaded)return;
	clearTimeout(nmenu.activePopupTimeout);
	if (nmenu.activePopup&&nmenu.activePopup.wid!=popupId+"popup")
		closePopup(nmenu,nmenu.activePopup.wid);
	if(popupId=='none')return;
	var rect;
	if(refWnd=='coords'){rect=getClientRect(document.layers[nmenu.name+'tl']);rect.left=rect.left+ml;rect.top=rect.top+mt;rect.right=rect.left+mr;rect.bottom=rect.top+mb;}else{rect=getClientRect(document.layers[popupId+"top"]);}
	var x;
	var y;
	if(nmenu.menuHorizontal)
	{
		x=rect.left;
		y=rect.bottom+nmenu.popupOffset;
	}
	else
	{
		x=rect.right+nmenu.popupOffset;
		y=rect.top;
	}
	if(nmenu.sepFrame&&!nmenu.openSameFrame)
	{
		var brRect=getBrowserRect(nmenu.popupFrame);
		var wRect=getBrowserRect(window);
		switch (nmenu.menuPos)
		{
		case 0:
			x=brRect.left+nmenu.popupOffset;
			y+=brRect.top-wRect.top;
			break;
		case 1:
			x=brRect.right-nmenu.popupOffset;
			y+=brRect.top-wRect.top;
			break;
		case 2:
			x+=brRect.left-wRect.left;
			y=brRect.top+nmenu.popupOffset;
			break;
		case 3:
			x+=brRect.left-wRect.left;
			y=brRect.bottom-nmenu.popupOffset;
			break;
		}
	}
	var popup=createPopupFromCode(nmenu,popupId,0);
	openPopup(nmenu,popup,x,y,true);
	nmenu.activePopup=popup;
}

function collapseMenu(nmenu,popupId)
{
	if(!docLoaded)return;
	var popup=eval("nmenu.popupFrame.document."+popupId+"popup");
	if(popup)onPopupOutImpl(nmenu,popup);
}

function expandMenuNS(nmenu,popupId,e)
{
	expandMenu(nmenu,popupId,e);
}

function collapseMenuNS(nmenu,popupId)
{
	collapseMenu(nmenu,popupId);
}

function onDocClick()
{
	var nmn;
	for(nmn=1;nmn<=lastm;nmn++)
	{
		var nmenu=eval("window.m"+nmn);
		if(nmenu&&nmenu.activePopup)closePopup(nmenu,nmenu.activePopup.wid);
	}
}

function findFrame(name)
{
	if(parent.frames[name])return parent.frames[name];
	var i;
	for(i=0;i<parent.frames.length;i++){if(parent.frames[i].frames[name])return parent.frames[i].frames[name];}
}

function initializeMenu()
{
	if(docLoaded)return;
	var nmn;
	for(nmn=1;nmn<=lastm;nmn++)
	{
		var nmenu=eval("window.m"+nmn);
		if(nmenu)
		{
			nmenu.popupFrame=(nmenu.sepFrame&&!nmenu.openSameFrame)?findFrame(nmenu.contentFrame):window;
			nmenu.targetFrame=(nmenu.sepFrame)?findFrame(nmenu.cntFrame):window;
			if(!nmenu.mout)addEvent(nmenu.popupFrame.document,"mousedown",onDocClick,false);
		}
	}
	docLoaded=true;
}

function addEvent(obj,event,fun,bubble)
{
	eval("obj.on"+event+"="+fun);
}

function chgBg(item,color)
{
}

function initializeAll()
{
	var i;
	for(i=0;i<=document.lastLoadHandler;i++)
	{
		eval(document.loadHandlers[i]+'();');
	}
}