// script generated by Xtreeme SiteXpert
// sitemap and search engine creator
// http://www.xtreeme.com/sitexpert
// Copyright(C) 2001-2002 Xtreeme GmbH

if (!document.loadHandlers)
{
	document.loadHandlers=new Array();
	document.loadHandlers[0]='initializeMenu';
	document.lastLoadHandler=0;
}
else
{
	document.lastLoadHandler++;
	document.loadHandlers[document.lastLoadHandler]='initializeMenu';
}
window.onload=initializeAll;
function errorTrap(){return true;}
window.onerror=errorTrap;

function resetPopup(popup)
{
	if(popup&&popup.children)
	{
		var i;
		for(i=0;i<popup.children.length;i++)
		{
			if(popup.children[i].id.indexOf('sep')==-1)
			{
				popup.children[i].style.color=popup.normalColor;
				popup.children[i].style.backgroundColor=popup.normalBgColor;
			}
		}
	}
}

function buildPopup(nmenu,arrayName,level)
{
	var levelAttribs;
	if (level > nmenu.maxlev) {levelAttribs = eval ("nmenu.lev" + nmenu.maxlev) ;} else {levelAttribs = eval ("nmenu.lev" + level) ;}
	var popupName=arrayName+"popup";
	nmenu.popupFrame.document.write("<div id='"+popupName+"' style='position:absolute;padding-left:"+nmenu.bord+";padding-top:"+nmenu.bord+";padding-right:"+nmenu.bord+";padding-bottom:"+nmenu.bord+";visibility:hidden'>");

	var array=eval(arrayName);
	var arrayItem;
	var ali=" align='"+(nmenu.popAlign==1?'center':(nmenu.popAlign==2?'right':'left'))+"' ";
	for(arrayItem=0;arrayItem<array.length/3;arrayItem++)
	{
		if (arrayItem>0&&nmenu.sep)nmenu.popupFrame.document.write("<div id='"+popupName+arrayItem+'sep'+"' style='background-color:"+nmenu.borderCol+";height:"+nmenu.sep+";width:"+(nmenu.popupWidth-nmenu.bord*2)+"'></div>");
		var popupArray=(array[arrayItem*3+2])?(arrayName+"_"+parseInt(arrayItem+1)):null;
		var iconTag=(array[arrayItem*3+2]?"<IMG SRC=\'"+(NS4?absPath:unescape(absPath))+nmenu.imgFolder+"/sxicona.gif\' BORDER=0 WIDTH="+nmenu.iconSize+" HEIGHT="+nmenu.iconSize+" HSPACE=0 ALIGN=RIGHT>":"");
		var itemText=array[arrayItem*3];
		var style="width:"+(nmenu.popupWidth-nmenu.bord*2-nmenu.vertSpace*2)+";padding-left:"+nmenu.vertSpace+";padding-top:"+nmenu.vertSpace+";padding-bottom:"+nmenu.vertSpace;
		style+=";font-size:"+levelAttribs[0]+";width:"+(nmenu.popupWidth-nmenu.vertSpace*2-nmenu.bord*2)+";color:"+levelAttribs[3]+";font-family:"+levelAttribs[6];
		if(levelAttribs[1])style+=";font-weight:bold";
		if(levelAttribs[2])style+=";font-style:italic";
		nmenu.popupFrame.document.write("<div"+ali+"id='"+(popupName+arrayItem)+"' style=\""+style+"\">"+iconTag+itemText+"</div>");
	}
	nmenu.popupFrame.document.write("<div style='height:0'>&nbsp;</div>");
	nmenu.popupFrame.document.write("</div>");
	for(arrayItem=0;arrayItem<array.length/3;arrayItem++)
	{
		if(array[arrayItem*3+2]) buildPopup(nmenu,arrayName+'_'+(arrayItem+1),level+1);
	}
}

function findFrame(name)
{
	if(parent.frames[name])return parent.frames[name];
	var i;
	for(i=0;i<parent.frames.length;i++){if(parent.frames[i].frames[name])return parent.frames[i].frames[name];}
}

function buildPopups()
{
	var nmn;
	var pf;
	for(nmn=1;nmn<=lastm;nmn++)
	{
		var nmenu=eval("window.m"+nmn);
		if(nmenu&&(!nmenu.sepFrame||nmenu.openSameFrame))
		{
			nmenu.popupFrame=(nmenu.sepFrame&&!nmenu.openSameFrame)?findFrame(nmenu.contentFrame):window;
			targetFrame=(nmenu.sepFrame)?findFrame(nmenu.cntFrame):window;
			var i=1;
			while(true)
			{
				var menu=eval(nmenu.name+'mn'+i);
				if (!menu)break;
				buildPopup(nmenu,nmenu.name+'mn'+i,0);
				i++;
			}
			pf=nmenu.popupFrame;
		}
	}
	if(pf)pf.document.close();
}

buildPopups ();

function createMenuItem(nmenu,popup,id,itemLink,itemText,popupArray,levelAttribs,bLast,popupHeight)
{
	var itemWnd=nmenu.popupFrame.document.getElementById(id);
	addEvent(itemWnd,"mouseover",onItemOver,false);
	addEvent(itemWnd,"mouseout",onItemOut,false);
	addEvent(itemWnd,"mousedown",onItemClick,false);
	addEvent(itemWnd,"dblclick",onItemClick,false);
	itemWnd.owner=popup;
	with (itemWnd.style)
	{
		if(itemLink){cursor="hand";}
		else{cursor="default";}
		backgroundColor=levelAttribs[4];
		setRealWidth(itemWnd,nmenu.popupWidth,2*nmenu.bord);
	}
	if (popupArray)itemWnd.popupArray=popupArray;
	if(itemLink&&itemLink.indexOf(':/')==-1&&itemLink.indexOf(':\\')==-1) itemWnd.url=unescape(absPath)+itemLink;
	else itemWnd.url=itemLink;
	itemWnd.dispText=itemText;
	if (0&&popupArray)
	{
		var expandArrow=nmenu.popupFrame.document.createElement("IMG");
		itemWnd.appendChild(expandArrow);
		expandArrow.src=unescape(absPath)+nmenu.imgFolder+"/sxicona.gif";
		with (expandArrow.style)
		{
			width=nmenu.iconSize;
			height=nmenu.iconSize;
			position="absolute";
			var itemRect=getClientRect(nmenu,itemWnd);
			top=(itemRect.bottom-itemRect.top)/2-nmenu.iconSize/2-2;
			left=itemWnd.offsetWidth-nmenu.iconSize-1;
		}
	}
	return itemWnd.offsetHeight;
}

function setRealWidth(wnd,width,borderWidth)
{
	wnd.style.pixelWidth=width-borderWidth;
	if (wnd.style.pixelWidth>width-borderWidth) wnd.style.pixelWidth=width-parseInt(wnd.style.paddingLeft)-parseInt(wnd.style.paddingRight);
}

function createPopupFromCode(nmenu,arrayName,level)
{
	var popupName=arrayName+"popup";
	var popup=nmenu.popupFrame.document.getElementById(popupName);
	if (popup&&popup.bCreated)return popup;
	var levelAttribs;
	if (level > nmenu.maxlev) {levelAttribs = eval ("nmenu.lev" + nmenu.maxlev) ;} else {levelAttribs = eval ("nmenu.lev" + level) ;}

	popup.level=level;
	popup.highlightColor=levelAttribs[5];
	popup.normalColor=levelAttribs[3];
	popup.highlightBgColor=levelAttribs[7];
	popup.normalBgColor=levelAttribs[4];
	popup.scrVis=false;
	popup.bCreated=true;
	popup.nmenu=nmenu;

	with (popup.style)
	{
		zIndex=maxZ;
		position="absolute";
		width=nmenu.popupWidth;
		borderColor=nmenu.borderCol;
		backgroundColor=nmenu.bord?nmenu.borderCol:levelAttribs[4];
		borderWidth=nmenu.bord;
		borderStyle="solid";
	}

	addEvent(popup,"mouseout",onPopupOut,false);
	addEvent(popup,"mouseover",onPopupOver,false);
	var popupHeight=0;

	var array=eval(arrayName);
	var arrayItem;
	for(arrayItem=0;arrayItem<array.length/3;arrayItem++)
	{
		var popupArray=(array[arrayItem*3+2])?(arrayName+"_"+parseInt(arrayItem+1)):null;
		popupHeight+=createMenuItem(nmenu,popup,(popupName+arrayItem),array[arrayItem*3+1],array[arrayItem*3],popupArray,levelAttribs,(arrayItem == array.length/3-1),popupHeight);
	}
	var bottomImgHeight=0;
	return popup;
}

function closePopup(nmenu,popupId)
{
	if(popupId.indexOf('_')==-1){var hideWnd=nmenu.popupFrame.document.getElementById('HideItem');if(hideWnd)hideWnd.style.visibility='visible';}
	var popup=nmenu.popupFrame.document.getElementById(popupId);
	if (popup)
	{
		resetPopup(popup);
		if (popup.expandedWnd) closePopup (nmenu,popup.expandedWnd.id);
		popup.style.visibility="hidden";
	}
	if (nmenu.activePopup && nmenu.activePopup.id==popupId) nmenu.activePopup=null;
}

function absToRel(rect,refx,refy)
{
	var retval=new rct(rect.left-refx,rect.top-refy,rect.right-refx,rect.bottom-refy);
	return retval;
}

function openPopup(nmenu,popup,x,y,bDontMove,refWnd)
{
	if(popup.id.indexOf('_')==-1){var hideWnd=nmenu.popupFrame.document.getElementById('HideItem');if(hideWnd)hideWnd.style.visibility='hidden';}
	popup.style.pixelLeft=x;
	popup.style.pixelTop=y;
	popup.style.visibility="visible";
	var popupRect=getClientRect(nmenu,popup);
	var browserRect=getBrowserRect(nmenu.popupFrame);
	if (popupRect.right>browserRect.right)
	{
		if(refWnd&&refWnd.id&&refWnd.id.indexOf('top')==-1)popup.style.pixelLeft=Math.max(0,refWnd.offsetLeft-popup.offsetWidth+nmenu.levelOffset);
		else popup.style.pixelLeft=browserRect.right-popup.offsetWidth-5;
	}
	//var cv=(nmenu.bIncBorder?3:20);
	//if ((popupRect.bottom>browserRect.bottom))
	//{
	//	var newtop=browserRect.bottom-popup.offsetHeight-cv;
	//	popup.style.pixelTop=newtop;
	//}
}

function isChildOfActivePopup(nmenu,popup)
{
	var wnd=nmenu.activePopup;
	while(wnd)
	{
		if (wnd.id==popup.id)
			return true;
		wnd=wnd.expandedWnd;
	}
	return false;
}

function onPopupOver()
{
	var nmenu=this.nmenu;
	if (nmenu.activePopup && isChildOfActivePopup (nmenu,this)) clearTimeout(nmenu.activePopupTimeout);
}

function onPopupOut()
{
	var nmenu=this.nmenu;
	onPopupOutImpl(nmenu,this);
}

function onPopupOutImpl(nmenu,popup)
{
	if (nmenu.mout && nmenu.activePopup && isChildOfActivePopup (nmenu,popup))
	{
		if (nmenu.activePopupTimeout) clearTimeout (nmenu.activePopupTimeout);
		nmenu.activePopupTimeout=setTimeout("closePopup("+nmenu.name+",'"+nmenu.activePopup.id+"');", nmenu.closeDelay);
	}
}

function rct(left,top,right,bottom)
{
	this.left=left;
	this.top=top;
	this.right=right;
	this.bottom=bottom;
}

function getBody(frame)
{
	var bodyArr=frame.document.getElementsByTagName('body');
	return bodyArr[0];
}

function getBrowserRect(doc)
{
	var body=getBody(doc);
	var left=body.style.pixelLeft;
	var top=body.style.pixelTop;
	var right=left+body.style.pixelWidth;
	var bottom=top+body.style.pixelHeight;
	var retval=new rct(left,top,right,bottom);
	return retval;	
}

function getClientRect(nmenu,wnd)
{
	var left=0;
	var top=0;
	var right=0;
	var bottom=0;
	var par=wnd;
	while (par)
	{
		left+=par.offsetLeft;
		top+=par.offsetTop;
		if (par.offsetParent==par || par.offsetParent==getBody(nmenu.popupFrame)) break;
		par=par.offsetParent;
	}
	right=left+wnd.offsetWidth;
	bottom=top+wnd.offsetHeight;
	var retval=new rct(left,top,right,bottom);
	return retval;
}

function onItemClick()
{
	var item=this;
	var nmenu=this.owner.nmenu;
	if (item.url)
	{
		var startPos=item.dispText.indexOf('<!--');
		if (startPos!=-1)
		{
			var endPos = item.dispText.indexOf('-->',startPos);
			var trgFrame = item.dispText.substring (startPos+4,endPos);
			if (trgFrame=="_blank") window.open (item.url);
			else if (trgFrame.indexOf('_')==0) parent.location.href=item.url;
			else eval("parent.frames."+trgFrame).location.href=item.url;
		}
		else
		{
			var find=item.url.indexOf("javascript:");
			if (find!=-1)
				eval(item.url.substring(find));
			else
				{
				var mt=item.url.indexOf("mailto:");
				if(mt!=-1)window.location=item.url.substring(mt);
				else if(nmenu.popupFrame!=window) window.open(item.url);
				else targetFrame.location=item.url;
				}
		}
		if(nmenu.activePopup)closePopup(nmenu,nmenu.activePopup.id);
	}
}

function onItemOver()
{
	var item=this;
	var nmenu=this.owner.nmenu;
	if (item.owner.expandedWnd)
	{
		resetPopup(item.owner);
		closePopup(nmenu,item.owner.expandedWnd.id);
	}
	if (item.url&&item.url.indexOf("javascript:")==-1)
		window.status=item.url;
	else
		window.status="";
	item.style.color=item.owner.highlightColor;
	item.style.backgroundColor=item.owner.highlightBgColor;
	var items=item.owner.getElementsByTagName("DIV");
	if (item.popupArray)
	{
		var rect=getClientRect(nmenu,item);
		var x=rect.right-nmenu.levelOffset;
		var y=rect.top;
		var popup=createPopupFromCode(nmenu,item.popupArray,item.owner.level+1);
		item.owner.expandedWnd=popup;
		openPopup(nmenu,popup,x,y+2,false,item.owner);
	}
}

function onItemOut()
{
	var item=this;
	var nmenu=this.owner.nmenu;
	item.style.color=item.owner.normalColor;
	item.style.backgroundColor=item.owner.normalBgColor;
}

function expandMenu(nmenu,popupId,refWnd,dum,ml,mt,mr,mb)
{
	if(!docLoaded)return;
	clearTimeout(nmenu.activePopupTimeout);
	if (nmenu.activePopup&&nmenu.activePopup.id!=popupId+"popup")
		closePopup(nmenu,nmenu.activePopup.id);
	if(popupId=='none')return;
	var rect;
	if(refWnd=='coords'){rect=getClientRect(nmenu,document.getElementById(nmenu.name+'tl'));rect.left=rect.left+ml;rect.top=rect.top+mt;rect.right=rect.left+mr;rect.bottom=rect.top+mb;}else{rect=getClientRect(nmenu,document.getElementById(refWnd));}
	var x;
	var y;
	if(nmenu.menuHorizontal)
	{
		x=rect.left;
		y=rect.bottom+nmenu.popupOffset;
	}
	else
	{
		x=rect.right+nmenu.popupOffset;
		y=rect.top;
	}
	if(nmenu.sepFrame&&!nmenu.openSameFrame)
	{
		var brRect=getBrowserRect(nmenu.popupFrame);
		var wRect=getBrowserRect(window);
		switch (nmenu.menuPos)
		{
		case 0:
			x=brRect.left+nmenu.popupOffset;
			y+=brRect.top-wRect.top;
			break;
		case 1:
			x=brRect.right-nmenu.popupOffset;
			y+=brRect.top-wRect.top;
			break;
		case 2:
			x+=brRect.left-wRect.left;
			y=brRect.top+nmenu.popupOffset;
			break;
		case 3:
			x+=brRect.left-wRect.left;
			y=brRect.bottom-nmenu.popupOffset;
			break;
		}
	}
	var popup=createPopupFromCode(nmenu,popupId,0);
	openPopup(nmenu,popup,x,y,true,null);
	nmenu.activePopup=popup;
}

function collapseMenu(nmenu,popupId)
{
	if(!docLoaded)return;
	var popup=nmenu.popupFrame.document.getElementById(popupId+"popup");
	if(popup)onPopupOutImpl(nmenu,popup);
}

function expandMenuNS(nmenu,popupId,e,dItem)
{
}

function collapseMenuNS(nmenu,popupId)
{
}

function onDocClick()
{
	var nmn;
	for(nmn=1;nmn<lastm;nmn++)
	{
		var nmenu=eval("window.m"+nmn);
		if(nmenu&&nmenu.activePopup)closePopup(nmenu,nmenu.activePopup.id);
	}
}

function initializeMenu()
{
	if(docLoaded)return;
	var nmn;
	for(nmn=1;nmn<lastm;nmn++)
	{
		var nmenu=eval("window.m"+nmn);
		if(nmenu&&!nmenu.mout)addEvent(nmenu.popupFrame.document,"mousedown",onDocClick,false);
	}
	docLoaded=true;
}

function addEvent(obj,event,fun,bubble)
{
	if (obj.addEventListener)
		obj.addEventListener(event,fun,bubble);
	else
		eval("obj.on"+event+"="+fun);
}

function chgBg(nmenu,item,color)
{
	var el=document.getElementById(item);
	if (color==0)
	{
		if(!nmenu.bBitmapScheme)el.style.background=nmenu.tlmOrigBg;
		el.style.color=nmenu.tlmOrigCol;
	}
	else
	{
		if(!nmenu.bBitmapScheme&&(color&1))el.style.background=nmenu.tlmHlBg ;
		if(color&2)el.style.color=nmenu.tlmHlCol ;
	}
}

function initializeAll()
{
	var i;
	for(i=0;i<=document.lastLoadHandler;i++)
	{
		eval(document.loadHandlers[i]+'();');
	}
}