document.write('<table width=\"760\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">');;
document.write('<tr>');
document.write('<td width=\"111\" valign=\"bottom\"><a href=\"index.html\"><img src=\"imagenes/logo.gif\" alt=\"SADM\" width=\"111\" height=\"111\" border=\"0\" /></a></td>');
document.write('<td width=\"100%\" valign=\"bottom\">');
document.write('<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">');
document.write('<tr>');
document.write('<td height=\"48\" valign=\"bottom\">');
document.write('<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">');
document.write('<tr>');
document.write('<td width=\"100%\">&nbsp;</td>');
document.write('<td width=\"149\" align=\"right\" nowrap=\"nowrap\" valign=\"middle\">');
document.write('<p><a href=\"index.html\" class=\"TopSubMenu\">Inicio</a><br />');
document.write('<a href=\"mapa_sitio.html\" class=\"TopSubMenu\">Mapa del Sitio</a><br />');
document.write('<a href=\"contactenos.html\" class=\"TopSubMenu\">Cont&aacute;ctenos</a></p>');
document.write('</td>');
document.write('</tr>');
document.write('</table>');
document.write('</td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td height=\"15\" valign=\"bottom\" class=\"TopAzul\">'); 
document.write('<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">');
document.write('<tr>');
document.write('<td><img src=\"imagenes/1.gif\" width=\"1\" height=\"1\" /></td>');
document.write('<td width=\"148\" align=\"right\"><img src=\"imagenes/top_cuadros.gif\" width=\"148\" height=\"15\" /></td>');
document.write('</tr>');
document.write('</table>');
document.write('</td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td height=\"26\" align=\"right\" class=\"TopGris\">');
document.write('<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">');
document.write('<tr>');
document.write('<td width=\"2\"><img src=\"imagenes/menu_separador.gif\" width=\"2\" height=\"26\" /></td>');
document.write('<td align=\"center\" nowrap=\"nowrap\" class=\"MenuRoof\" onmouseover=\"Change_roofBar(this,1);expandMenu(m1,'m1mn1','m1tlm0',event)\" onmouseout=\"Change_roofBar(this,0);collapseMenu(m1,'m1mn1');\" onclick=\"roofBar_Click(this,'#');\" id=\"m1tlm0\"><span class=\"MenuRoof\"><a id=\"m1tlm0a\" href=\"#\"  onmouseover=\"expandMenuNS(m1,'m1mn1',event)\" onmouseout=\"collapseMenuNS(m1,'m1mn1');\" ><div id='m1mn1top'>¿Quiénes Somos?</div></a></span></td>');
document.write('<td width=\"2\"><img src=\"imagenes/menu_separador.gif\" width=\"2\" height=\"26\" /></td>');
document.write('<td align=\"center\" nowrap=\"nowrap\" class=\"MenuRoof\" onmouseover=\"Change_roofBar(this,1);expandMenu(m1,'m1mn2','m1tlm1',event)\" onmouseout=\"Change_roofBar(this,0);collapseMenu(m1,'m1mn2');\" onclick=\"roofBar_Click(this,'#');\" id=\"m1tlm1\"><span class=\"MenuRoof\"><a id=\"m1tlm1a\" href=\"#\"  onmouseover=\"expandMenuNS(m1,'m1mn2',event)\" onmouseout=\"collapseMenuNS(m1,'m1mn2');\" ><div id='m1mn2top'>Requisitos para Contratar</div></a></span></td>');
document.write('<td width=\"2\"><img src=\"imagenes/menu_separador.gif\" width=\"2\" height=\"26\" /></td>');
document.write('<td align=\"center\" nowrap=\"nowrap\" class=\"MenuRoof\" onmouseover=\"Change_roofBar(this,1);expandMenu(m1,'m1mn3','m1tlm2',event)\" onmouseout=\"Change_roofBar(this,0);collapseMenu(m1,'m1mn3');\" onclick=\"roofBar_Click(this,'#');\" id=\"m1tlm2\"><span class=\"MenuRoof\"><a id=\"m1tlm2a\" href=\"#\"  onmouseover=\"expandMenuNS(m1,'m1mn3',event)\" onmouseout=\"collapseMenuNS(m1,'m1mn3');\" ><div id='m1mn3top'>Pago de Servicios</div></a></span></td>');
document.write('<td width=\"2\"><img src=\"imagenes/menu_separador.gif\" width=\"2\" height=\"26\" /></td>');
document.write('<td align=\"center\" nowrap=\"nowrap\" class=\"MenuRoof\" onmouseover=\"Change_roofBar(this,1);expandMenu(m1,'none','',event)\" onmouseout=\"Change_roofBar(this,0)\" onclick=\"roofBar_Click(this,'#');\" id=\"m1tlm3\"><span class=\"MenuRoof\"><a id=\"m1tlm3a\" href=\"informacion_servicios.html\"><div id='m1mn4top'>Centro de Información y Servicio</div></a></span></td>');
document.write('<td width=\"2\"><img src=\"imagenes/menu_separador.gif\" width=\"2\" height=\"26\" /></td>');
document.write('<td align=\"center\" nowrap=\"nowrap\" class=\"MenuRoof\" onmouseover=\"Change_roofBar(this,1);expandMenu(m1,'m1mn5','m1tlm4',event)\" onmouseout=\"Change_roofBar(this,0);collapseMenu(m1,'m1mn5');\" onclick=\"roofBar_Click(this,'#');\" id=\"m1tlm4\"><span class=\"MenuRoof\"><a id=\"m1tlm4a\" href=\"#\"  onmouseover=\"expandMenuNS(m1,'m1mn5',event)\" onmouseout=\"collapseMenuNS(m1,'m1mn5');\" ><div id='m1mn5top'>Programas</div></a></span></td>');
document.write('<td width=\"2\"><img src=\"imagenes/menu_separador.gif\" width=\"2\" height=\"26\" /></td>');
document.write('<td align=\"center\" nowrap=\"nowrap\" class=\"MenuRoof\" onmouseover=\"Change_roofBar(this,1);expandMenu(m1,'m1mn6','m1tlm5',event)\" onmouseout=\"Change_roofBar(this,0);collapseMenu(m1,'m1mn6')\" onclick=\"roofBar_Click(this,'#');\" id=\"m1tlm5\"><span class=\"MenuRoof\"><a id=\"m1tlm5a\" href=\"#\" onmouseover=\"expandMenuNS(m1,'m1mn6',event)\" onMouseOut=\"collapseMenuNS(m1,'m1mn6')\" ><div id='m1mn6top'>Ttransparencia</div></a></span></td>');
document.write('</tr>');
document.write('</table>');
document.write('</td>');
document.write('</tr>');
document.write('</table>');
document.write('</td>');
document.write('</tr>');
document.write('</table>');