/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2021-09-07 16:14:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.FileInputStream;
import java.util.Properties;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.text.DateFormat;
import java.util.Date;
import java.util.Calendar;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import org.json.JSONArray;
import java.util.Random;
import org.json.JSONObject;
import java.io.InputStreamReader;
import org.json.JSONException;
import java.util.logging.Logger;
import java.util.logging.Level;
import java.io.IOException;
import java.io.BufferedReader;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.URL;

public final class Cna_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/Top.jsp", Long.valueOf(1630099373576L));
    _jspx_dependants.put("/MenuServicios.jsp", Long.valueOf(1630099372646L));
    _jspx_dependants.put("/HeaderOptions.jsp", Long.valueOf(1630099372078L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.net.HttpURLConnection");
    _jspx_imports_classes.add("java.util.Properties");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.net.URL");
    _jspx_imports_classes.add("java.time.LocalDateTime");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.util.Random");
    _jspx_imports_classes.add("java.io.IOException");
    _jspx_imports_classes.add("java.io.FileInputStream");
    _jspx_imports_classes.add("java.util.logging.Logger");
    _jspx_imports_classes.add("java.io.InputStreamReader");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("java.util.logging.Level");
    _jspx_imports_classes.add("org.json.JSONException");
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("org.json.JSONObject");
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
    _jspx_imports_classes.add("java.io.BufferedReader");
    _jspx_imports_classes.add("java.text.DateFormat");
    _jspx_imports_classes.add("org.json.JSONArray");
    _jspx_imports_classes.add("java.io.InputStream");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    HttpSession objSession = request.getSession(false);
    String usuario = (String) objSession.getAttribute("usuario");
    String nombreusuario = (String) objSession.getAttribute("nombreusuario");
    String token = (String) objSession.getAttribute("token");
    if (null == usuario) {
        System.out.println("success HttpSession FALSE:::::");
        out.println("<script type=\"text/javascript\">");
        out.println("window.parent.location.href='sweetAlert.html'");
        out.println("</script>");
    } else if (usuario.equals("")) {
        System.out.println("success HttpSession FALSE:::::");
        out.println("<script type=\"text/javascript\">");
        out.println("window.parent.location.href='sweetAlert.html'");
        out.println("</script>");
    } else {
        ArrayList<String> lstnis = new ArrayList<String>();
        String strNombreLegible = new String(nombreusuario.getBytes("ISO-8859-1"), "UTF-8");
        InputStream isArchivo = new FileInputStream((String) objSession.getAttribute("urlProperties"));
        Properties oProperties = new Properties();
        oProperties.load(isArchivo);
         String INICIO = oProperties.getProperty("INICIO");


      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html charset=utf-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("        ");
      out.write("<link href=\"imagenes/logo_transp.gif\" rel=\"shortcut icon\" type=\"image/x-icon\" />\n");
      out.write("<link href=\"imagenes/logo_transp.gif\" rel=\"apple-touch-icon\" />\n");
      out.write("<link href=\"styles/normalize.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<link href=\"styles/main.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<link href=\"styles/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700\" rel=\"stylesheet\"> \n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery3.js\"></script>\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("<link href=\"styles/webflow1.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<link href=\"styles/webflow4.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<link href=\"styles/webflow3.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<script language=\"JavaScript\" src=\"js/script.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script>\n");
      out.write("<!-- CSS only -->\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x\" crossorigin=\"anonymous\">\n");
      out.write("<!-- JavaScript Bundle with Popper -->\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script language=\"JavaScript\" src=\"js/script.js\"></script>\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.min.js\" type=\"text/javascript\" integrity=\"sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://uploads-ssl.webflow.com/5ad759a356a64144486fd75f/js/webflow.d69d0ec41.js\" type=\"text/javascript\"></script>\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.11.2/jquery-ui.js\"></script>");
      out.write("\n");
      out.write("        <title>Pago de Servicios - VPC</title>\n");
      out.write("        <link href=\"styles/webflow1.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <link href=\"styles/webflow4.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <link href=\"styles/webflow3.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <link href=\"styles/web.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <link href=\"styles/bootstrap-grid.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\" integrity=\"sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh\" crossorigin=\"anonymous\">\n");
      out.write("    </head>\n");
      out.write("    <body onload=\"numcol()\" oncontextmenu=\"return false;\">\n");
      out.write("        <!-- HEADER -->\n");
      out.write("        <div id=\"content\">\n");
      out.write("            ");
      out.write("<style>\n");
      out.write("    a{\n");
      out.write("        text-decoration: none !important;\n");
      out.write("    }\n");
      out.write("    a:hover{\n");
      out.write("        text-decoration: none !important;\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("<script>\n");
      out.write("var lastScrollTop = 0;\n");
      out.write("$(window).scroll(function(event){\n");
      out.write("   var st = $(this).scrollTop();\n");
      out.write("   if (st > lastScrollTop){\n");
      out.write("       // downscroll code\n");
      out.write("       document.getElementById(\"TopMenu\").style.display = \"none\"\n");
      out.write("   } else {\n");
      out.write("      // upscroll code\n");
      out.write("      document.getElementById(\"TopMenu\").style.display = \"inline\"\n");
      out.write("   }\n");
      out.write("   lastScrollTop = st;\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<div  data-ix=\"move-down-on-load\" id=\"TopMenu\" data-w-id=\"151ec016-beb1-b657-3bb7-0a531105cafe\" class=\"top-bar\" style=\"opacity: 1; transform: translateX(0px) translateY(0%) translateZ(0px); transition: opacity 200ms ease 0s, transform 800ms ease 0s;\">\n");
      out.write("    <div data-collapse=\"medium\" data-animation=\"default\" data-duration=\"400\" id=\"Top\" class=\"navbar-1 w-nav\">\n");
      out.write("        <div class=\"content-wrapper w-container\">\n");
      out.write("            <script>\n");
      out.write("                function logoref() {\n");
      out.write("                    top.location.href = \"https://web.sadm.gob.mx/\";\n");
      out.write("                }\n");
      out.write("            </script>\n");
      out.write("            <a onclick=\"logoref()\" data-ix=\"fade-out-on-click\" class=\"brand w-nav-brand w--current\">\n");
      out.write("                <img src=\"images/AYD.png\" srcset=\"https://uploads-ssl.webflow.com/5ad759a356a64144486fd75f/5b6b5f504c3819038b156e33_logo%20sadm-p-500.png 500w, https://uploads-ssl.webflow.com/5ad759a356a64144486fd75f/5b6b5f504c3819038b156e33_logo%20sadm-p-800.png 800w, https://uploads-ssl.webflow.com/5ad759a356a64144486fd75f/5b6b5f504c3819038b156e33_logo%20sadm-p-1080.png 1080w, https://uploads-ssl.webflow.com/5ad759a356a64144486fd75f/5b6b5f504c3819038b156e33_logo%20sadm.png 1217w\" sizes=\"(max-width: 479px) 79vw, (max-width: 767px) 192px, 202px\">\n");
      out.write("            </a>\n");
      out.write("            <nav role=\"navigation\" class=\"w-nav-menu\">\n");
      out.write("                <a id=\"inicio\" onclick=\"inicioref()\" data-ix=\"fade-out-on-click\" class=\"navlink w-nav-link\" style=\"max-width: 1170px;\">\n");
      out.write("                    <script>\n");
      out.write("                        function inicioref() {\n");
      out.write("                            top.location.href = \"https://web.sadm.gob.mx/\";\n");
      out.write("                        }\n");
      out.write("                    </script>\n");
      out.write("                    Inicio\n");
      out.write("                </a>\n");
      out.write("                <a id=\"consulta-en-linea\" onclick=\"consultaref()\"  data-ix=\"fade-out-on-click\" class=\"navlink w-nav-link\" style=\"max-width: 1170px;\">\n");
      out.write("                    <script>\n");
      out.write("                        function consultaref() {\n");
      out.write("                            top.location.href = \"https://ayd.sadm.gob.mx/eAyd/\";\n");
      out.write("                        }\n");
      out.write("                    </script>\n");
      out.write("                    Consulta en Línea\n");
      out.write("                </a>                        \n");
      out.write("                <a id=\"pago-en-linea\" onclick=\"pagoref()\" data-ix=\"fade-out-on-click\" class=\"navlink w-nav-link\" style=\"max-width: 1170px;\">\n");
      out.write("                    <script>\n");
      out.write("                        function pagoref() {\n");
      out.write("                            top.location.href = \"https://ayd.sadm.gob.mx/eAyd/\";\n");
      out.write("                        }\n");
      out.write("                    </script>\n");
      out.write("                    Pago en Línea\n");
      out.write("                </a>\n");
      out.write("                <a id=\"factibilidades\" onclick=\"factibilidadesref()\" data-ix=\"fade-out-on-click\" class=\"navlink w-nav-link\" style=\"max-width: 1170px;\">\n");
      out.write("                    <script>\n");
      out.write("                        function factibilidadesref() {\n");
      out.write("                            top.location.href = \"https://ayd.sadm.gob.mx/eClickEnLinea/\";\n");
      out.write("                        }\n");
      out.write("                    </script>\n");
      out.write("                    Factibilidades\n");
      out.write("                </a>      \n");
      out.write("\n");
      out.write("            </nav>\n");
      out.write("            <div class=\"menu-button w-nav-button\">\n");
      out.write("                <div>\n");
      out.write("                    <div class=\"line-1\"></div>\n");
      out.write("                    <div class=\"line-2\"></div>\n");
      out.write("                    <div class=\"line-3\"></div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <div class=\"w-nav-overlay\" data-wf-ignore=\"\"></div>\n");
      out.write("    </div>\n");
      out.write("<br></div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            <br>\n");
      out.write("\n");
      out.write("\n");
      out.write("            <div class=\"container-fluid my-4\">\n");
      out.write("                <div class=\"row py2\">\n");
      out.write("                    <div class=\"container py2\">\n");
      out.write("\n");
      out.write("                      ");
      out.write("<style>\n");
      out.write("    @media screen and (min-width: 0px) and (max-width: 720px) {\n");
      out.write("        #datos_usuario2 { display: none; }.mobile-hide{ display: none; }\n");
      out.write("        \n");
      out.write("    }\n");
      out.write("    @media screen and (min-width: 720px)  {\n");
      out.write("        #datos_usuario3 { display: none; }.mobile-hide{ display: none; }\n");
      out.write("        \n");
      out.write("    }\n");
      out.write("    \n");
      out.write("</style>\n");
      out.write("<div class=\"col-12 col-lg-3 float-left\" >\n");
      out.write("    <div  id=\"datos_usuario2\" >\n");
      out.write("        <div id=\"opcionesMenu\" class=\"card my-2\" >\n");
      out.write("\n");
      out.write("            <div id=\"header-card\" class=\"card-header\">\n");
      out.write("                <label for=\"nombre\">Nombre:</label>\n");
      out.write("                <input id=\"nombre\" class=\"form-control\" type=\"text\" value=\"");
      out.print(strNombreLegible);
      out.write("\" disabled=\"disabled\" />\n");
      out.write("                <label for=\"email\">E-mail:</label>\n");
      out.write("                <input id=\"email\" class=\"form-control\" type=\"text\" value=\"");
      out.print(usuario);
      out.write("\" disabled=\"disabled\" />\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <ul id=\"menu-lateral\" class=\"list-group\">\n");
      out.write("                <li class=\"list-group-item list-group-item-action \" title=\"Servicios Asignados en mi cuenta.\">\n");
      out.write("                    <a href=\"");
      out.print(INICIO);
      out.write("\"><i class=\"fa fa-address-card-o\" aria-hidden=\"true\"></i> Servicios Asignados</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"list-group-item list-group-item-action \" title=\"Agregar un nuevo servicio a mi cuenta.\">\n");
      out.write("                    <a href=\"AgregarServicio.jsp\"><i class=\"fa fa-plus\" aria-hidden=\"true\"></i> Agregar Servicio</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"list-group-item list-group-item-action\"title=\"Notificar mis Alertas por Correo.\">\n");
      out.write("                    <a href=\"ServiciosAlertas.jsp\"><i class=\"fa fa-bell-o\" aria-hidden=\"true\"></i> Servicios de Alertas</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"list-group-item list-group-item-action\"title=\"Carta de no Adeudo\">\n");
      out.write("                    <a href=\"Cna.jsp\"><i class=\"fa fa-bell-o\" aria-hidden=\"true\"></i>Carta de No Adeudo</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"list-group-item list-group-item-action\" title=\"Modificar mi Información\">\n");
      out.write("                    <a href=\"UserEdit.jsp\"><i class=\"fa fa-pencil-square-o\" aria-hidden=\"true\"></i> Modificar Datos</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"list-group-item list-group-item-action\" title=\"Genera reportes operativos\">\n");
      out.write("                    <a href=\"Reportes.jsp\"><i class=\"fa fa-pencil-square-o\" aria-hidden=\"true\"></i> Reportes</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"list-group-item list-group-item-action\" title=\"Cerrar mi Sesión.\">\n");
      out.write("                    <form action=\"cerrarsesion\"   method=\"post\" id=\"formsalir\" name=\"formsalir\" >\n");
      out.write("                        <a onclick=\"cerrarsesion()\"><i class=\"fa fa-sign-out\" aria-hidden=\"true\"></i> Cerrar Sesión</a>\n");
      out.write("                    </form>\n");
      out.write("                    <script>\n");
      out.write("                        function cerrarsesion() {\n");
      out.write("                            $(\"#formsalir\").submit();\n");
      out.write("                        }\n");
      out.write("                    </script>\n");
      out.write("                </li></ul>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <div id=\"datos_usuario3\"  >\n");
      out.write("        <nav class=\"navbar navbar-expand-sm navbar-light bg-light\">\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#opciones\">\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("    </button>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <!-- enlaces -->\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"opciones\">   \n");
      out.write("      <ul class=\"navbar-nav\">\n");
      out.write("        <li class=\"nav-item\">\n");
      out.write("         <a class=\"nav-link\" href=\"");
      out.print(INICIO);
      out.write("\">Servicios Asignados</a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"nav-item\">\n");
      out.write("         <a class=\"nav-link\"  href=\"AgregarServicio.jsp\">Agregar Servicio</a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link\" href=\"ServiciosAlertas.jsp\"> Servicios de Alertas</a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link\" href=\"Cna.jsp\"> Carta de No Adeudo</a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link\" href=\"UserEdit.jsp\"> Modificar Datos</a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link\" href=\"Reportes.jsp\">Reportes</a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link\" href=\"cerrarsesion\">Cerrar Sesión</a>\n");
      out.write("        </li>\n");
      out.write("      </ul>\n");
      out.write("    </div>\n");
      out.write("  </nav>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("                        <div id=\"tblServicios\" class=\"col-12 col-lg-9 float-left\">\n");
      out.write("                            <div id=\"contenido_informacion1\" >\n");
      out.write("                                <script>\n");
      out.write("                                    function numcol() {\n");
      out.write("                                        let params = new URLSearchParams(location.search);\n");
      out.write("                                        var cartamsj = params.get('cartamsj');\n");
      out.write("\n");
      out.write("                                        if (\"null\" === cartamsj) {\n");
      out.write("                                            document.getElementById(\"AvisoCNATrue\").hidden = false;\n");
      out.write("                                            document.getElementById(\"AvisoCNAFalse\").hidden = false;\n");
      out.write("                                        } else if (cartamsj === \"0\") {\n");
      out.write("\n");
      out.write("                                            var cmsj = params.get('cmsj');\n");
      out.write("                                            cmsj = cmsj.replace('�?', 'Á');\n");
      out.write("\n");
      out.write("                                            document.getElementById(\"AvisoCNATrue\").hidden = true;\n");
      out.write("                                            document.getElementById(\"AvisoCNAFalse\").hidden = false;\n");
      out.write("                                            document.getElementById(\"cmsj\").innerHTML = cmsj;\n");
      out.write("                                        } else if (cartamsj === \"1\") {\n");
      out.write("                                            document.getElementById(\"AvisoCNATrue\").hidden = false;\n");
      out.write("                                            document.getElementById(\"AvisoCNAFalse\").hidden = true;\n");
      out.write("\n");
      out.write("                                        }\n");
      out.write("                                        var rows = document.getElementById('tabla_servicios1').getElementsByTagName('tbody')[0].getElementsByTagName('tr').length - 2;\n");
      out.write("                                        if (rows !== 0) {\n");
      out.write("                                            var colum = \"Tiene \" + rows + \" servicios asignados a su Cuenta en Línea:\";\n");
      out.write("                                            document.getElementById(\"h4Table\").innerHTML = colum;\n");
      out.write("                                            document.getElementById(\"Total\").value = \"0.00\";\n");
      out.write("                                            document.getElementById(\"tblServicios\").hidden = false;\n");
      out.write("                                            document.getElementById(\"h4Table2\").hidden = true;\n");
      out.write("                                            document.getElementById(\"h6Table2\").hidden = true;\n");
      out.write("                                        } else {\n");
      out.write("                                            var colum = \"No tiene servicios asignados en tu Línea. \";\n");
      out.write("                                            document.getElementById(\"h4Table2\").innerHTML = colum;\n");
      out.write("\n");
      out.write("                                            document.getElementById(\"tblServicios\").hidden = true;\n");
      out.write("                                            document.getElementById(\"h4Table2\").hidden = false;\n");
      out.write("                                            document.getElementById(\"h6Table2\").hidden = false;\n");
      out.write("                                        }\n");
      out.write("                                    }\n");
      out.write("                                </script>\n");
      out.write("\n");
      out.write("                                <!-- <label id=\"h4Table\" style=\"font-family: 'Roboto', sans-serif;font-size: 16px;font-weight: 300;color:#3c4858;\" >Seleccione el servicio que desee para que le llegue un aviso a su correo electrónico. Puede cambiar su selección cuando guste.</label>-->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                                <table  class=\"table table-sm table-responsive table-striped\" id=\"tabla_servicios1\">\n");
      out.write("                                    <tbody>\n");
      out.write("                                        <tr class=\"encabezado\" id=\"servico_encabezado\">\n");
      out.write("                                            <th align=\"center\" width=\"10%\"><b>Contrato</b></th>\n");
      out.write("                                            <th align=\"center\" width=\"30%\"><b>Dirección</b></th>\n");
      out.write("                                            <th align=\"center\" width=\"20%\"><b>Saldo</b></th>\n");
      out.write("                                            <th align=\"center\"  width=\"25%\"><b>Carta de No Adeudo</b></th>\n");
      out.write("\n");
      out.write("                                        </tr>\n");
      out.write("\n");
      out.write("                                        ");

                                            
                                            String SELSALDOS = oProperties.getProperty("SELSALDOS");

                                            URL url = new URL(SELSALDOS + usuario);
                                            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
                                            conn.setRequestMethod("GET");
                                            conn.setRequestProperty("Accept", "application/json");
                                            conn.setRequestProperty("Authorization", "Bearer " + token);

                                            //System.out.println("conn.getResponseCode() :: "+conn.getResponseCode());
                                            if (conn.getResponseCode() != 200) {
                                                System.out.println("Failed login : HTTP error code : " + conn.getResponseCode());
                                                response.sendRedirect("Login.jsp");
                                                //throw new RuntimeException("Failed : HTTP error code : " + conn.getResponseCode());

                                            } else {
                                                try {

                                                    InputStream inputStream = conn.getInputStream();
                                                    String json = new String();
                                                    BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(inputStream), 1);
                                                    String line;
                                                    while ((line = bufferedReader.readLine()) != null) {
                                                        json = line;
                                                    }
                                                    inputStream.close();
                                                    bufferedReader.close();
                                                    // System.out.println("SELSALDOS json ::: " + json);
                                                    JSONObject jsonObj = new JSONObject(json);

                                                    JSONObject jsonObjservresponse = new JSONObject(jsonObj.get("Response").toString());
                                                    //System.out.println("SELSALDOS strjsonObjservresponsedata :: " +jsonObjservresponse.toString());
                                                    String strjsonObjservresponsedata = jsonObjservresponse.get("data").toString();

                                                    strjsonObjservresponsedata = strjsonObjservresponsedata.replace("[", "");
                                                    strjsonObjservresponsedata = strjsonObjservresponsedata.replace("]", "");

                                                    // System.out.println("strjsonObjservresponsedata :: " + strjsonObjservresponsedata);
                                                    JSONObject jsonObjservresponsedata = new JSONObject(strjsonObjservresponsedata);
                                                    //System.out.println("jsonObjservresponsedata :: " + jsonObjservresponsedata.toString());

                                                    JSONArray results = new JSONArray(jsonObjservresponse.get("data").toString());
                                                    //System.out.println("result:: " + results.length());
                                                    for (int i = 0; i < results.length(); i++) {
                                        
      out.write("\n");
      out.write("                                        <tr>\n");
      out.write("                                            ");

                                                 JSONObject aux = results.getJSONObject(i);
//                                                System.out.println("NIS: "+aux.get("NIS").toString());
//                                                 System.out.println("Direccion: "+aux.get("Direccion").toString());
//                                                 System.out.println("Total "+aux.get("v_totaladeu").toString());
                                                String nisfact = aux.get("NIS").toString();
                                                lstnis.add(nisfact);
                                                String strDomicilio = "" + aux.get("Direccion").toString() + " ";
                                                String strdomicilioLegible = new String(strDomicilio.getBytes("ISO-8859-1"), "UTF-8");
                                                double dbtotal = Double.parseDouble(aux.get("v_totaladeu").toString());
                                            
      out.write("\n");
      out.write("                                            <td align=\"center\" width=\"10%\">");
      out.print(aux.get("NIS").toString());
      out.write("&nbsp;</td>\n");
      out.write("\n");
      out.write("                                            <td width=\"50%\">");
      out.print(strdomicilioLegible);
      out.write(" </td>\n");
      out.write("\n");
      out.write("                                            <td width=\"8%\">");
      out.print(dbtotal);
      out.write("&nbsp;</td>\n");
      out.write("                                            ");

                                                if (aux.get("v_totaladeu").toString().equalsIgnoreCase("0.00") || aux.get("v_totaladeu").toString().equalsIgnoreCase("0")) {
                                            
      out.write("\n");
      out.write("\n");
      out.write("                                            <td style=\"text-align: center;\" ><input class=\"btn btn-outline-secondary2\" type=\"button\" value=\"Solicitar\" onclick=\"solicitarCarta('");
      out.print(aux.get("NIS").toString());
      out.write("', '");
      out.print(usuario);
      out.write("')\"></td>                                  \n");
      out.write("                                                ");

                                                } else {
                                                
      out.write("\n");
      out.write("                                            <td style=\"text-align: center;\" width=\"5%\"> <a href=\"");
      out.print(INICIO);
      out.write("\"><i class=\"fa fa-address-card-o\" aria-hidden=\"true\"></i>Pagar</a></td>\n");
      out.write("\n");
      out.write("                                            ");
}
      out.write("\n");
      out.write("\n");
      out.write("                                        </tr>\n");
      out.write("                                        <tr>\n");
      out.write("                                            <td align=\"center\" width=\"10%\"></td>\n");
      out.write("\n");
      out.write("                                            <td width=\"50%\"></td>\n");
      out.write("\n");
      out.write("                                            <td width=\"8%\"></td>\n");
      out.write("                                            <td style=\"text-align: center;\" width=\"5%\"> </td>\n");
      out.write("\n");
      out.write("                                        </tr>\n");
      out.write("                                        ");

                                                    }

                                                } catch (IOException ioe) {

                                                } catch (JSONException ex) {

                                                }
                                            }

                                        
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                                    </tbody></table>\n");
      out.write("                                <hr>\n");
      out.write("                                <div class=\"text-right\" >\n");
      out.write("\n");
      out.write("                                    Para generar la Carta de No Adeudo, se debe cubrir el saldo en el servicio.&nbsp;&nbsp;&nbsp;\n");
      out.write("\n");
      out.write("                                </div>\n");
      out.write("                                <hr>\n");
      out.write("                                <div hidden id=\"AvisoCNATrue\" class=\"alert alert-success text-center alert-link\" role=\"alert\"> <i class=\"fas fa-check-circle fa-lg\"></i> Carta de No Adeudos enviada con éxito.  <label>Por Favor revise su correo en un momento.</label></div>\n");
      out.write("                                <div hidden id=\"AvisoCNAFalse\" class=\"alert alert-danger text-center alert-link\" role=\"alert\"> <i class=\"fas fa-check-circle fa-lg\"></i> Carta no enviada. <label id=\"cmsj\"></label></div>\n");
      out.write("\n");
      out.write("                                <script>\n");
      out.write("                                    function solicitarCarta(nis, correo) {\n");
      out.write("\n");
      out.write("                                        document.getElementById(\"niscarta\").value = nis;\n");
      out.write("                                        document.getElementById(\"emailcarta\").value = correo;\n");
      out.write("                                        document.getElementById(\"solicitarCartaFrom\").submit();\n");
      out.write("                                    }\n");
      out.write("                                </script> \n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("            <div>\n");
      out.write("                <form id=\"solicitarCartaFrom\" name=\"solicitarCartaFrom\" method=\"POST\" action=\"solicitarcarta\">\n");
      out.write("                    <input id=\"niscarta\" name=\"niscarta\" hidden >\n");
      out.write("                    <input id=\"emailcarta\" name=\"emailcarta\" hidden >\n");
      out.write("                </form>\n");
      out.write("            </div></div>\n");
      out.write("                                        \n");
      out.write("    </body>\n");
      out.write("</html>\n");
}
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
