/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2021-09-07 16:14:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ayd.dao.RutaProperties;
import java.util.Properties;
import java.io.FileInputStream;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.text.DateFormat;
import java.util.Date;
import java.util.Calendar;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import org.json.JSONArray;
import java.util.Random;
import org.json.JSONObject;
import java.io.InputStreamReader;
import org.json.JSONException;
import java.util.logging.Logger;
import java.util.logging.Level;
import java.io.IOException;
import java.io.BufferedReader;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.URL;

public final class Inicio_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/Bottom.jsp", Long.valueOf(1630099370741L));
    _jspx_dependants.put("/Top.jsp", Long.valueOf(1630099373576L));
    _jspx_dependants.put("/MenuServicios.jsp", Long.valueOf(1630099372646L));
    _jspx_dependants.put("/HeaderOptions.jsp", Long.valueOf(1630099372078L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.net.HttpURLConnection");
    _jspx_imports_classes.add("java.util.Properties");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.net.URL");
    _jspx_imports_classes.add("java.time.LocalDateTime");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.util.Random");
    _jspx_imports_classes.add("java.io.IOException");
    _jspx_imports_classes.add("java.io.FileInputStream");
    _jspx_imports_classes.add("java.util.logging.Logger");
    _jspx_imports_classes.add("java.io.InputStreamReader");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("java.util.logging.Level");
    _jspx_imports_classes.add("org.json.JSONException");
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("org.json.JSONObject");
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
    _jspx_imports_classes.add("com.ayd.dao.RutaProperties");
    _jspx_imports_classes.add("java.io.BufferedReader");
    _jspx_imports_classes.add("java.text.DateFormat");
    _jspx_imports_classes.add("org.json.JSONArray");
    _jspx_imports_classes.add("java.io.InputStream");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    HttpSession objSession = request.getSession(false);
    String usuario = (String) objSession.getAttribute("usuario");
//    System.out.println("usuario inicio sesion:: " + usuario);
    String nombreusuario = (String) objSession.getAttribute("nombreusuario");
    String token = (String) objSession.getAttribute("token");
    if (null == usuario) {
        System.out.println("success HttpSession FALSE:::::");
        out.println("<script type=\"text/javascript\">");
        out.println("window.parent.location.href='sweetAlert.html'");
        out.println("</script>");
    } else if (usuario.equals("")) {
        System.out.println("success HttpSession FALSE:::::");
        out.println("<script type=\"text/javascript\">");
        out.println("window.parent.location.href='sweetAlert.html'");
        out.println("</script>");
    } else {
        ArrayList<String> lstnis = new ArrayList<String>();
        String strNombreLegible = new String(nombreusuario.getBytes("ISO-8859-1"), "UTF-8");
        RutaProperties rp = new RutaProperties();
        String urlProperties = rp.getRuta();
        objSession.setAttribute("urlProperties", urlProperties);
        InputStream isArchivo = new FileInputStream((String) objSession.getAttribute("urlProperties"));
        Properties oProperties = new Properties();
        oProperties.load(isArchivo);
        String INICIO = oProperties.getProperty("INICIO");
        if (INICIO.equalsIgnoreCase("InicioControl.jsp")) {
            System.out.println("Inicio redirecciona a InicioCOntrol por Properties detectado");
            response.sendRedirect(INICIO);
        }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <link href=\"imagenes/logo_transp.gif\" rel=\"shortcut icon\" type=\"image/x-icon\" />\n");
      out.write("        <link href=\"imagenes/logo_transp.gif\" rel=\"apple-touch-icon\" />\n");
      out.write("        <meta name=\"tipo_contenido\"  content=\"text/html;\" http-equiv=\"content-type\" charset=\"utf-8\">\n");
      out.write("        <script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html charset=utf-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("        ");
      out.write("<link href=\"imagenes/logo_transp.gif\" rel=\"shortcut icon\" type=\"image/x-icon\" />\n");
      out.write("<link href=\"imagenes/logo_transp.gif\" rel=\"apple-touch-icon\" />\n");
      out.write("<link href=\"styles/normalize.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<link href=\"styles/main.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<link href=\"styles/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700\" rel=\"stylesheet\"> \n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery3.js\"></script>\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("<link href=\"styles/webflow1.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<link href=\"styles/webflow4.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<link href=\"styles/webflow3.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<script language=\"JavaScript\" src=\"js/script.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script>\n");
      out.write("<!-- CSS only -->\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x\" crossorigin=\"anonymous\">\n");
      out.write("<!-- JavaScript Bundle with Popper -->\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script language=\"JavaScript\" src=\"js/script.js\"></script>\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.min.js\" type=\"text/javascript\" integrity=\"sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://uploads-ssl.webflow.com/5ad759a356a64144486fd75f/js/webflow.d69d0ec41.js\" type=\"text/javascript\"></script>\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.11.2/jquery-ui.js\"></script>");
      out.write("\n");
      out.write("        <title>Pago de Servicios - VPC</title>\n");
      out.write("        <link href=\"styles/webflow1.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <link href=\"styles/webflow4.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <link href=\"styles/webflow3.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <script language=\"JavaScript\" src=\"js/script.js\"></script>\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\n");
      out.write("        <script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\n");
      out.write("        <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script>\n");
      out.write("        <style>\n");
      out.write("            #loading {\n");
      out.write("                width: 100%;\n");
      out.write("                height: 100%;\n");
      out.write("                top: 0;\n");
      out.write("                left: 0;\n");
      out.write("                position: fixed;\n");
      out.write("                display: block;\n");
      out.write("                opacity: 0.7;\n");
      out.write("                background-color: #fff;\n");
      out.write("                z-index: 99;\n");
      out.write("                text-align: center;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            #loading-image {\n");
      out.write("                position: absolute;\n");
      out.write("                top: 100px;\n");
      out.write("                left: 240px;\n");
      out.write("                z-index: 100;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("        <script type=\"text/javascript\" >\n");
      out.write("            $(document).ready(function () {\n");
      out.write("                setTimeout(function () {\n");
      out.write("                    $(\".loading\").hide();\n");
      out.write("                }, 1000);\n");
      out.write("\n");
      out.write("               \n");
      out.write("            });\n");
      out.write("        </script>\n");
      out.write("    </head\n");
      out.write("\n");
      out.write("    <body  onload=\"numcol()\" oncontextmenu=\"return false;\">\n");
      out.write("        <div class=\"loading\" id=\"loading\" >\n");
      out.write("            <br><br><br><br>\n");
      out.write("            <br><br><br><br>\n");
      out.write("            <br><br><br><br>\n");
      out.write("            <br><br><br><br>\n");
      out.write("            <center>\n");
      out.write("                <div class=\"spinner-border text-primary\" style=\"width: 15rem; height: 15rem;\" role=\"status\">\n");
      out.write("                    <span class=\"sr-only\">Loading...</span>\n");
      out.write("                </div>\n");
      out.write("            </center>\n");
      out.write("        </div>\n");
      out.write("        <SCRIPT LANGUAGE=\"JavaScript\">\n");
      out.write("            history.forward()\n");
      out.write("        </SCRIPT>\n");
      out.write("        ");
      out.write("<style>\n");
      out.write("    a{\n");
      out.write("        text-decoration: none !important;\n");
      out.write("    }\n");
      out.write("    a:hover{\n");
      out.write("        text-decoration: none !important;\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("<script>\n");
      out.write("var lastScrollTop = 0;\n");
      out.write("$(window).scroll(function(event){\n");
      out.write("   var st = $(this).scrollTop();\n");
      out.write("   if (st > lastScrollTop){\n");
      out.write("       // downscroll code\n");
      out.write("       document.getElementById(\"TopMenu\").style.display = \"none\"\n");
      out.write("   } else {\n");
      out.write("      // upscroll code\n");
      out.write("      document.getElementById(\"TopMenu\").style.display = \"inline\"\n");
      out.write("   }\n");
      out.write("   lastScrollTop = st;\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<div  data-ix=\"move-down-on-load\" id=\"TopMenu\" data-w-id=\"151ec016-beb1-b657-3bb7-0a531105cafe\" class=\"top-bar\" style=\"opacity: 1; transform: translateX(0px) translateY(0%) translateZ(0px); transition: opacity 200ms ease 0s, transform 800ms ease 0s;\">\n");
      out.write("    <div data-collapse=\"medium\" data-animation=\"default\" data-duration=\"400\" id=\"Top\" class=\"navbar-1 w-nav\">\n");
      out.write("        <div class=\"content-wrapper w-container\">\n");
      out.write("            <script>\n");
      out.write("                function logoref() {\n");
      out.write("                    top.location.href = \"https://web.sadm.gob.mx/\";\n");
      out.write("                }\n");
      out.write("            </script>\n");
      out.write("            <a onclick=\"logoref()\" data-ix=\"fade-out-on-click\" class=\"brand w-nav-brand w--current\">\n");
      out.write("                <img src=\"images/AYD.png\" srcset=\"https://uploads-ssl.webflow.com/5ad759a356a64144486fd75f/5b6b5f504c3819038b156e33_logo%20sadm-p-500.png 500w, https://uploads-ssl.webflow.com/5ad759a356a64144486fd75f/5b6b5f504c3819038b156e33_logo%20sadm-p-800.png 800w, https://uploads-ssl.webflow.com/5ad759a356a64144486fd75f/5b6b5f504c3819038b156e33_logo%20sadm-p-1080.png 1080w, https://uploads-ssl.webflow.com/5ad759a356a64144486fd75f/5b6b5f504c3819038b156e33_logo%20sadm.png 1217w\" sizes=\"(max-width: 479px) 79vw, (max-width: 767px) 192px, 202px\">\n");
      out.write("            </a>\n");
      out.write("            <nav role=\"navigation\" class=\"w-nav-menu\">\n");
      out.write("                <a id=\"inicio\" onclick=\"inicioref()\" data-ix=\"fade-out-on-click\" class=\"navlink w-nav-link\" style=\"max-width: 1170px;\">\n");
      out.write("                    <script>\n");
      out.write("                        function inicioref() {\n");
      out.write("                            top.location.href = \"https://web.sadm.gob.mx/\";\n");
      out.write("                        }\n");
      out.write("                    </script>\n");
      out.write("                    Inicio\n");
      out.write("                </a>\n");
      out.write("                <a id=\"consulta-en-linea\" onclick=\"consultaref()\"  data-ix=\"fade-out-on-click\" class=\"navlink w-nav-link\" style=\"max-width: 1170px;\">\n");
      out.write("                    <script>\n");
      out.write("                        function consultaref() {\n");
      out.write("                            top.location.href = \"https://ayd.sadm.gob.mx/eAyd/\";\n");
      out.write("                        }\n");
      out.write("                    </script>\n");
      out.write("                    Consulta en Línea\n");
      out.write("                </a>                        \n");
      out.write("                <a id=\"pago-en-linea\" onclick=\"pagoref()\" data-ix=\"fade-out-on-click\" class=\"navlink w-nav-link\" style=\"max-width: 1170px;\">\n");
      out.write("                    <script>\n");
      out.write("                        function pagoref() {\n");
      out.write("                            top.location.href = \"https://ayd.sadm.gob.mx/eAyd/\";\n");
      out.write("                        }\n");
      out.write("                    </script>\n");
      out.write("                    Pago en Línea\n");
      out.write("                </a>\n");
      out.write("                <a id=\"factibilidades\" onclick=\"factibilidadesref()\" data-ix=\"fade-out-on-click\" class=\"navlink w-nav-link\" style=\"max-width: 1170px;\">\n");
      out.write("                    <script>\n");
      out.write("                        function factibilidadesref() {\n");
      out.write("                            top.location.href = \"https://ayd.sadm.gob.mx/eClickEnLinea/\";\n");
      out.write("                        }\n");
      out.write("                    </script>\n");
      out.write("                    Factibilidades\n");
      out.write("                </a>      \n");
      out.write("\n");
      out.write("            </nav>\n");
      out.write("            <div class=\"menu-button w-nav-button\">\n");
      out.write("                <div>\n");
      out.write("                    <div class=\"line-1\"></div>\n");
      out.write("                    <div class=\"line-2\"></div>\n");
      out.write("                    <div class=\"line-3\"></div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <div class=\"w-nav-overlay\" data-wf-ignore=\"\"></div>\n");
      out.write("    </div>\n");
      out.write("<br></div>\n");
      out.write("\n");
      out.write("        <!-- HEADER -->\n");
      out.write("        <div id=\"content\">\n");
      out.write("            <div class=\"container-fluid my-4\">\n");
      out.write("                <div class=\"row py2\">\n");
      out.write("                    <div class=\"container py2\">\n");
      out.write("\n");
      out.write("                        ");
      out.write("<style>\n");
      out.write("    @media screen and (min-width: 0px) and (max-width: 720px) {\n");
      out.write("        #datos_usuario2 { display: none; }.mobile-hide{ display: none; }\n");
      out.write("        \n");
      out.write("    }\n");
      out.write("    @media screen and (min-width: 720px)  {\n");
      out.write("        #datos_usuario3 { display: none; }.mobile-hide{ display: none; }\n");
      out.write("        \n");
      out.write("    }\n");
      out.write("    \n");
      out.write("</style>\n");
      out.write("<div class=\"col-12 col-lg-3 float-left\" >\n");
      out.write("    <div  id=\"datos_usuario2\" >\n");
      out.write("        <div id=\"opcionesMenu\" class=\"card my-2\" >\n");
      out.write("\n");
      out.write("            <div id=\"header-card\" class=\"card-header\">\n");
      out.write("                <label for=\"nombre\">Nombre:</label>\n");
      out.write("                <input id=\"nombre\" class=\"form-control\" type=\"text\" value=\"");
      out.print(strNombreLegible);
      out.write("\" disabled=\"disabled\" />\n");
      out.write("                <label for=\"email\">E-mail:</label>\n");
      out.write("                <input id=\"email\" class=\"form-control\" type=\"text\" value=\"");
      out.print(usuario);
      out.write("\" disabled=\"disabled\" />\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <ul id=\"menu-lateral\" class=\"list-group\">\n");
      out.write("                <li class=\"list-group-item list-group-item-action \" title=\"Servicios Asignados en mi cuenta.\">\n");
      out.write("                    <a href=\"");
      out.print(INICIO);
      out.write("\"><i class=\"fa fa-address-card-o\" aria-hidden=\"true\"></i> Servicios Asignados</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"list-group-item list-group-item-action \" title=\"Agregar un nuevo servicio a mi cuenta.\">\n");
      out.write("                    <a href=\"AgregarServicio.jsp\"><i class=\"fa fa-plus\" aria-hidden=\"true\"></i> Agregar Servicio</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"list-group-item list-group-item-action\"title=\"Notificar mis Alertas por Correo.\">\n");
      out.write("                    <a href=\"ServiciosAlertas.jsp\"><i class=\"fa fa-bell-o\" aria-hidden=\"true\"></i> Servicios de Alertas</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"list-group-item list-group-item-action\"title=\"Carta de no Adeudo\">\n");
      out.write("                    <a href=\"Cna.jsp\"><i class=\"fa fa-bell-o\" aria-hidden=\"true\"></i>Carta de No Adeudo</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"list-group-item list-group-item-action\" title=\"Modificar mi Información\">\n");
      out.write("                    <a href=\"UserEdit.jsp\"><i class=\"fa fa-pencil-square-o\" aria-hidden=\"true\"></i> Modificar Datos</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"list-group-item list-group-item-action\" title=\"Genera reportes operativos\">\n");
      out.write("                    <a href=\"Reportes.jsp\"><i class=\"fa fa-pencil-square-o\" aria-hidden=\"true\"></i> Reportes</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"list-group-item list-group-item-action\" title=\"Cerrar mi Sesión.\">\n");
      out.write("                    <form action=\"cerrarsesion\"   method=\"post\" id=\"formsalir\" name=\"formsalir\" >\n");
      out.write("                        <a onclick=\"cerrarsesion()\"><i class=\"fa fa-sign-out\" aria-hidden=\"true\"></i> Cerrar Sesión</a>\n");
      out.write("                    </form>\n");
      out.write("                    <script>\n");
      out.write("                        function cerrarsesion() {\n");
      out.write("                            $(\"#formsalir\").submit();\n");
      out.write("                        }\n");
      out.write("                    </script>\n");
      out.write("                </li></ul>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <div id=\"datos_usuario3\"  >\n");
      out.write("        <nav class=\"navbar navbar-expand-sm navbar-light bg-light\">\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#opciones\">\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("    </button>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <!-- enlaces -->\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"opciones\">   \n");
      out.write("      <ul class=\"navbar-nav\">\n");
      out.write("        <li class=\"nav-item\">\n");
      out.write("         <a class=\"nav-link\" href=\"");
      out.print(INICIO);
      out.write("\">Servicios Asignados</a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"nav-item\">\n");
      out.write("         <a class=\"nav-link\"  href=\"AgregarServicio.jsp\">Agregar Servicio</a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link\" href=\"ServiciosAlertas.jsp\"> Servicios de Alertas</a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link\" href=\"Cna.jsp\"> Carta de No Adeudo</a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link\" href=\"UserEdit.jsp\"> Modificar Datos</a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link\" href=\"Reportes.jsp\">Reportes</a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link\" href=\"cerrarsesion\">Cerrar Sesión</a>\n");
      out.write("        </li>\n");
      out.write("      </ul>\n");
      out.write("    </div>\n");
      out.write("  </nav>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <h4 id=\"h4Table2\" class=\"mb-3\" style=\"color:#3c4858;\" ></h4><h6 id=\"h6Table2\" title=\"Agregar un servicio\">Para agregar un servicio presiona <a href=\"AgregarServicio.jsp\">Aquí</a></h6>\n");
      out.write("                        <div id=\"tblServicios\" class=\"col-12 col-lg-9 float-left\">\n");
      out.write("                            <div id=\"contenido_informacion1\" >\n");
      out.write("                                <script>\n");
      out.write("                                    function numcol() {\n");
      out.write("                                        var rows = document.getElementById('tabla_servicios1').getElementsByTagName('tbody')[0].getElementsByTagName('tr').length - 2;\n");
      out.write("                                        if (rows !== 0) {\n");
      out.write("                                            var colum = \"Tiene \" + rows + \" servicios asignados a su Cuenta en Línea:\";\n");
      out.write("                                            document.getElementById(\"h4Table\").innerHTML = colum;\n");
      out.write("                                            document.getElementById(\"Total\").value = \"0\";\n");
      out.write("                                            document.getElementById(\"tblServicios\").hidden = false;\n");
      out.write("                                            document.getElementById(\"h4Table2\").hidden = true;\n");
      out.write("                                            document.getElementById(\"h6Table2\").hidden = true;\n");
      out.write("                                        } else {\n");
      out.write("                                            var colum = \"No tiene servicios asignados en tu Línea. \";\n");
      out.write("                                            document.getElementById(\"h4Table2\").innerHTML = colum;\n");
      out.write("                                            document.getElementById(\"tblServicios\").hidden = true;\n");
      out.write("                                            document.getElementById(\"h4Table2\").hidden = false;\n");
      out.write("                                            document.getElementById(\"h6Table2\").hidden = false;\n");
      out.write("                                        }\n");
      out.write("                                    }\n");
      out.write("                                </script>\n");
      out.write("\n");
      out.write("                                <label id=\"h4Table\" style=\"font-family: 'Roboto', sans-serif;font-size: 16px;font-weight: 300;color:#3c4858;\" >Seleccione el servicio que desee para que le llegue un aviso a su correo electrónico. Pude cambiar su selección cuando guste.</label>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                                <table  class=\"table table-sm table-responsive table-striped\" id=\"tabla_servicios1\">\n");
      out.write("                                    <tbody>\n");
      out.write("                                        <tr class=\"encabezado\" id=\"servico_encabezado\">\n");
      out.write("                                            <th style=\"text-align: center\" align=\"center\" width=\"5%\">Eliminar</th>\n");
      out.write("                                            <th style=\"text-align: center\" align=\"center\" width=\"10%\"><b>Contrato</b></th>\n");
      out.write("                                            <th align=\"center\" width=\"7%\"><b>Consultar Recibo</b></th>\n");
      out.write("                                            <th style=\"text-align: center\" align=\"center\" width=\"70%\"><b>Dirección</b></th>\n");
      out.write("                                            <th style=\"text-align: center\" align=\"center\" width=\"18%\"><b>Fecha de Vencimiento</b></th>\n");
      out.write("                                            <th style=\"text-align: center\" align=\"center\" width=\"5%\"><b>Importe</b></th>\n");
      out.write("\n");
      out.write("                                            <th  style=\"text-align: center\" align=\"center\" width=\"5%\">&nbsp;$&nbsp;</th>\n");
      out.write("\n");
      out.write("                                        </tr>\n");
      out.write("\n");
      out.write("                                        ");

                                            String SELSALDOS = oProperties.getProperty("SELSALDOS");

                                            URL url = new URL(SELSALDOS + usuario);
                                            System.out.println(token + "::: SELSALDOs ::: " + url);
                                            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
                                            conn.setRequestMethod("GET");
                                            conn.setRequestProperty("Accept", "application/json");
                                            conn.setRequestProperty("Authorization", "Bearer " + token);

                                            System.out.println("conn.getResponseCode() :: " + conn.getResponseCode());
                                            if (conn.getResponseCode() != 200) {
                                                //System.out.println("Failed login : HTTP error code : " + conn.getResponseCode());
                                                response.sendRedirect("Login.jsp");
                                                //throw new RuntimeException("Failed : HTTP error code : " + conn.getResponseCode());

                                            } else {
                                                try {

                                                    InputStream inputStream = conn.getInputStream();
                                                    String json = new String();
                                                    BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(inputStream), 1);
                                                    String line;
                                                    while ((line = bufferedReader.readLine()) != null) {
                                                        json = line;
                                                    }
                                                    inputStream.close();
                                                    bufferedReader.close();
                                                    //System.out.println("SELSALDOS json ::: " + json);
                                                    JSONObject jsonObj = new JSONObject(json);

                                                    JSONObject jsonObjservresponse = new JSONObject(jsonObj.get("Response").toString());
                                                    //System.out.println("SELSALDOS strjsonObjservresponsedata :: " +jsonObjservresponse.toString());
                                                    String strjsonObjservresponsedata = jsonObjservresponse.get("data").toString();

                                                    strjsonObjservresponsedata = strjsonObjservresponsedata.replace("[", "");
                                                    strjsonObjservresponsedata = strjsonObjservresponsedata.replace("]", "");

                                                    // System.out.println("strjsonObjservresponsedata :: " + strjsonObjservresponsedata);
                                                    JSONObject jsonObjservresponsedata = new JSONObject(strjsonObjservresponsedata);
                                                    //System.out.println("jsonObjservresponsedata :: " + jsonObjservresponsedata.toString());

                                                    JSONArray results = new JSONArray(jsonObjservresponse.get("data").toString());
                                                    //System.out.println("result:: " + results.length());
                                                    for (int i = 0; i < results.length(); i++) {
                                        
      out.write("\n");
      out.write("                                        <tr>\n");
      out.write("                                            ");

                                                JSONObject aux = results.getJSONObject(i);
                                                //System.out.println("NIS: " + aux.get("NIS").toString());
                                                //                                                 System.out.println("Direccion: "+aux.get("Direccion").toString());
                                                //                                                 System.out.println("Total "+aux.get("v_totaladeu").toString());
                                                String nisfact = aux.get("NIS").toString();
                                                lstnis.add(nisfact);
                                                String strDomicilio = "" + aux.get("Direccion").toString() + " ";
                                                String strdomicilioLegible = new String(strDomicilio.getBytes("ISO-8859-1"), "UTF-8");

                                            
      out.write("\n");
      out.write("                                            <td  align=\"center\" width=\"7%\"><input type=\"image\" name=\"EliminaServicio\" onclick=\"eliminarServicio('");
      out.print(aux.get("NIS").toString());
      out.write("');\" src=\"imagenes/eliminar.png\" style=\"width: 25px; height: 25px;\" title=\"Eliminar Servicio\" ></td>\n");
      out.write("                                            <td align=\"center\" width=\"10%\">");
      out.print(aux.get("NIS").toString());
      out.write("&nbsp;</td>\n");
      out.write("                                            <td align=\"center\" width=\"7%\">\n");
      out.write("                                                <a href=\"#facturaModal");
      out.print(aux.get("NIS").toString());
      out.write("\" id=\"dialog\"  class=\"btn btn-info btn-sm\"  data-toggle=\"modal\" data-target=\"#facturaModal");
      out.print(aux.get("NIS").toString());
      out.write("\"><i class=\"fa fa-search\" aria-hidden=\"true\"></i>\n");
      out.write("                                                    Ver Facturas</a>\n");
      out.write("                                            </td>\n");
      out.write("                                            <td width=\"50%\">");
      out.print(strdomicilioLegible);
      out.write(" </td>\n");
      out.write("                                            <td align=\"center\" width=\"8%\">");
      out.print(aux.get("Fecha_Venc").toString());
      out.write("&nbsp;</td>\n");
      out.write("                                            ");
 double dbamount = Double.parseDouble(aux.get("v_totaladeu").toString());
      out.write("\n");
      out.write("                                            <td width=\"8%\">");
      out.print(dbamount);
      out.write("&nbsp;</td>\n");
      out.write("\n");
      out.write("                                            ");

                                                if (aux.get("v_totaladeu").toString().equalsIgnoreCase("0.00") || aux.get("v_totaladeu").toString().equalsIgnoreCase("0")) {
                                            
      out.write("\n");
      out.write("                                            <td align=\"center\" width=\"5%\"><font class=\"comment\">Sin adeudos</font></td>\n");
      out.write("                                                ");

                                                } else {
                                                
      out.write("\n");
      out.write("                                            <td   align=\"center\"  width=\"5%\"><input id=\"");
      out.print(aux.get("NIS").toString());
      out.write("\" onclick=\"agregarmonto('");
      out.print(aux.get("v_totaladeu".toString()));
      out.write("', '");
      out.print(aux.get("NIS".toString()));
      out.write("', '");
      out.print(aux.get("Vencimiento").toString());
      out.write("', '");
      out.print(aux.get("Fecha_Venc").toString());
      out.write("')\" type=\"checkbox\" class=\"only-one\"></td>\n");
      out.write("\n");
      out.write("                                            ");
}
      out.write("\n");
      out.write("\n");
      out.write("                                        </tr>\n");
      out.write("                                        ");

                                                    }

                                                } catch (IOException ioe) {

                                                } catch (JSONException ex) {

                                                }
                                            }


                                        
      out.write("\n");
      out.write("                                    <script>\n");
      out.write("                                        function agregarmonto(p1, p2, p3, p4) {\n");
      out.write("\n");
      out.write("\n");
      out.write("                                            if (document.getElementById(p2).checked) {\n");
      out.write("                                                document.getElementById(\"nispagar\").value = document.getElementById(\"nispagar\").value + p2 + \"nis\";\n");
      out.write("                                                document.getElementById(\"nispagardt\").value = document.getElementById(\"nispagardt\").value + p2 + \"_\" + p3 + \"_\" + p4 + \"_\" + p1 + \"nis\";\n");
      out.write("                                                var montochk = new Number(p1);\n");
      out.write("                                                montototal = 0;\n");
      out.write("                                                var montototal = new Number(document.getElementById(\"Total\").value);\n");
      out.write("                                                document.getElementById(\"Total\").value = \"\";\n");
      out.write("                                                var montototal = montototal + montochk;\n");
      out.write("                                                document.getElementById(\"Total\").value = montototal + \"\";\n");
      out.write("                                                document.getElementById(\"checkactive\").value = document.getElementById(\"checkactive\").value + 1;\n");
      out.write("                                            } else {\n");
      out.write("                                                if (document.getElementById(\"Total\").value !== \"0\") {\n");
      out.write("                                                    var nis = document.getElementById(\"nispagar\").value;\n");
      out.write("                                                    nis = nis.replace(p2 + \"nis\", \"\");\n");
      out.write("                                                    document.getElementById(\"nispagar\").value = nis;\n");
      out.write("                                                    var nisdt = document.getElementById(\"nispagardt\").value;\n");
      out.write("                                                    nisdt = nisdt.replace(p2 + \"_\" + p3 + \"_\" + p4 + \"_\" + p1 + \"nis\", \"\");\n");
      out.write("                                                    document.getElementById(\"nispagardt\").value = nisdt;\n");
      out.write("                                                    var montochk = new Number(p1);\n");
      out.write("                                                    montototal = 0;\n");
      out.write("                                                    var montototal = new Number(document.getElementById(\"Total\").value);\n");
      out.write("                                                    document.getElementById(\"Total\").value = \"\";\n");
      out.write("                                                    var montototal = montototal - montochk;\n");
      out.write("                                                    document.getElementById(\"Total\").value = montototal + \"\";\n");
      out.write("                                                    document.getElementById(\"checkactive\").value = document.getElementById(\"checkactive\").value - 1;\n");
      out.write("                                                } else {\n");
      out.write("                                                    document.getElementById(\"montopagar\").value = \"0\";\n");
      out.write("                                                }\n");
      out.write("                                            }\n");
      out.write("\n");
      out.write("\n");
      out.write("                                        }\n");
      out.write("\n");
      out.write("                                        function eliminarServicio(p1) {\n");
      out.write("                                            document.getElementById(\"v_nis_rad\").value = p1;\n");
      out.write("                                            swal({\n");
      out.write("                                                title: \"¿Desea eliminar el contrato \" + p1 + \"?\",\n");
      out.write("                                                text: \"Se eliminara de la lista de tus servicios.\",\n");
      out.write("                                                icon: \"warning\",\n");
      out.write("                                                buttons: true,\n");
      out.write("                                                dangerMode: true,\n");
      out.write("                                            })\n");
      out.write("                                                    .then((willDelete) => {\n");
      out.write("                                                        if (willDelete) {\n");
      out.write("                                                            swal(\"Eliminado! El NIS fue eliminado!\", {\n");
      out.write("                                                                icon: \"success\",\n");
      out.write("                                                            });\n");
      out.write("                                                            document.deleteServForm.submit();\n");
      out.write("                                                        } else {\n");
      out.write("                                                            swal(\"El nis no fué eliminado!\");\n");
      out.write("                                                            document.getElementById(\"v_nis_rad\").value = \"\";\n");
      out.write("                                                        }\n");
      out.write("                                                    });\n");
      out.write("                                        }\n");
      out.write("                                    </script>\n");
      out.write("\n");
      out.write("                                    <tr  class=\"trtotal\" id=\"trtotal\">\n");
      out.write("                                        <td align=\"right\" colspan=\"5\"><font class=\"text\"><b>Total a pagar :&nbsp;</b></font></td>\n");
      out.write("\n");
      out.write("                                        <td colspan=\"2\"><input readonly  type=\"text\"  id=\"Total\" name=\"Total\" class=\"default\" size=\"12\" ></td>\n");
      out.write("\n");
      out.write("                                    </tr>\n");
      out.write("\n");
      out.write("                                    </tbody></table>\n");
      out.write("                                <div class=\"text-right\">\n");
      out.write("\n");
      out.write("                                    <input  class=\"btn btn-outline-secondary2\" id=\"btn_submit\" type=\"button\" value=\"Pagar Servicios\" onclick=\"pagarServcicios();\">&nbsp;&nbsp;&nbsp;\n");
      out.write("\n");
      out.write("\n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div >\n");
      out.write("                <form name=\"deleteServForm\" method=\"POST\" action=\"servicedelete\">\n");
      out.write("\n");
      out.write("                    <input id=\"v_nis_rad\" name=\"v_nis_rad\" hidden>\n");
      out.write("                    <input id=\"Email\" name=\"Email\" value='");
      out.print(usuario);
      out.write("' hidden>\n");
      out.write("                    <input id=\"token\" name=\"token\" value='");
      out.print(token);
      out.write("' hidden>\n");
      out.write("\n");
      out.write("                </form>\n");
      out.write("            </div>                       \n");
      out.write("\n");
      out.write("\n");
      out.write("            ");
//SELFACTURAS DESHABILITADO
                //System.out.println("lstnis size:: " + lstnis.size());
                for (String s : lstnis) {
                    //System.out.println("s ::" + s);
            
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("            <div class=\"modal fade\" id=\"facturaModal");
      out.print(s);
      out.write("\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\" style=\"margin-top: 150px;\">\n");
      out.write("                <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("                    <div class=\"modal-content\">\n");
      out.write("                        <div class=\"modal-header\">\n");
      out.write("                            <h5 class=\"modal-title\" id=\"facturaModalLabel\">Facturas</h5>\n");
      out.write("                            <input id=\"nisfacturas\" hidden >\n");
      out.write("                            <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("                                <span aria-hidden=\"true\">&times;</span>\n");
      out.write("                            </button>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"modal-body\">\n");
      out.write("                            <div id=\"listado\">\n");
      out.write("                                <style>\n");
      out.write("                                    /* LIST #4 */\n");
      out.write("                                    #listado { width:360px; font-family:Georgia, Times, serif; font-size:15px; }\n");
      out.write("                                    #listado ul { list-style: none; }\n");
      out.write("                                    #listado ul li { }\n");
      out.write("                                    #listado ul li a { display:block; text-decoration:none; color:#000000; background-color:#FFFFFF; line-height:30px;\n");
      out.write("                                                       border-bottom-style:solid; border-bottom-width:1px; border-bottom-color:#CCCCCC; padding-left:10px; cursor:pointer; }\n");
      out.write("                                    #listado ul li a:hover { color:#FFFFFF; background-image:url(images/hover.png); background-repeat:repeat-x; }\n");
      out.write("                                    #listado ul li a strong { margin-right:10px; }\n");
      out.write("                                </style>\n");
      out.write("\n");
      out.write("                                ");

                                    String SELFACTURAS = oProperties.getProperty("SELFACTURAS");

                                    URL urlfacturas = new URL(SELFACTURAS + s);
                                    //System.out.println("urlfacturas :: " + urlfacturas);
                                    HttpURLConnection connfacturas = (HttpURLConnection) urlfacturas.openConnection();
                                    connfacturas.setRequestMethod("GET");
                                    connfacturas.setRequestProperty("Accept", "application/json");
                                    connfacturas.setRequestProperty("Authorization", "Bearer " + token);
                                    //System.out.println("connfacturas.getResponseCode() :: " + connfacturas.getResponseCode());
                                    if (connfacturas.getResponseCode() != 200) {

                                        System.out.println("SELFACTURAS RESPOSE CODE: " + connfacturas.getResponseCode());
                                        //response.sendRedirect(INICIO);

                                        //throw new RuntimeException("Failed : HTTP error code : " + connfacturas.getResponseCode());
                                    } else {
                                        InputStream inputStreamfactura = connfacturas.getInputStream();
                                        String jsonfacturas = new String();
                                        BufferedReader bufferedReaderfactura = new BufferedReader(new InputStreamReader(inputStreamfactura), 1);
                                        String linefacturas;
                                        while ((linefacturas = bufferedReaderfactura.readLine()) != null) {
                                            jsonfacturas = linefacturas;
//                                            System.out.println("jsonfacturas " + s + "::: " + jsonfacturas);
                                        }
                                        inputStreamfactura.close();
                                        bufferedReaderfactura.close();
                                        JSONObject jsonObjfacturas = new JSONObject(jsonfacturas);
                                        //System.out.println("jsonfacturas " + s + "::: " + jsonfacturas.toString());
                                        //success
                                        if (jsonObjfacturas.get("success").toString().equalsIgnoreCase("true")) {
                                            JSONObject jsonObjfacturasresponse = new JSONObject(jsonObjfacturas.get("Response").toString());
                                            String strjsonObjfactresponsedata = jsonObjfacturasresponse.get("data").toString();

                                            strjsonObjfactresponsedata = strjsonObjfactresponsedata.replace("[", "");
                                            strjsonObjfactresponsedata = strjsonObjfactresponsedata.replace("]", "");

//                                        System.out.println("strjsonObjservresponsedata :: " + strjsonObjfactresponsedata);
                                            JSONArray results = new JSONArray(jsonObjfacturasresponse.get("data").toString());
//                                        System.out.println("result fact:: " + results.length());
                                
      out.write("\n");
      out.write("                                <ul>\n");
      out.write("                                    ");

                                        for (int i = 0; i < results.length(); i++) {
                                            JSONObject fact = results.getJSONObject(i);
//                                            System.out.println("fact ::" + fact.getString("PDF").toString());
//                                            System.out.println("fact ::" + fact.getString("XML").toString());
//                                            System.out.println("fact ::" + fact.getString("TO_CHAR").toString());
                                    
      out.write("\n");
      out.write("                                    <li><a href=\"");
      out.print(fact.getString("PDF").toString());
      out.write("\" target=\"_blank\">");
      out.print(fact.getString("TO_CHAR").toString());
      out.write("&nbsp; (pdf)</a></li>\n");
      out.write("                                    <li><a href=\"");
      out.print(fact.getString("XML").toString());
      out.write("\" target=\"_blank\">");
      out.print(fact.getString("TO_CHAR").toString());
      out.write("&nbsp; (xml)</a></li>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                                    ");

                                        }
      out.write("\n");
      out.write("                                </ul>\n");
      out.write("                                ");

                                } else {
                                    System.out.println("SELFACTURAS con success false, se invita a volver a intentarlo mas tarde en modal para permitir continuar reaizar pagos");
                                
      out.write("\n");
      out.write("                                <h3>Este servicio no está disponible en este momento.</h3>\n");
      out.write("                                <h5>Ya estamos trabajando para mejorar la consulta de sus facturas.</h5>\n");
      out.write("                                <h6>Agradecemos su comprensión. Vuelva a intentar más tarde.</h6>\n");
      out.write("\n");
      out.write("                                ");

                                        }
                                    }
                                
      out.write("\n");
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            ");
}
      out.write("\n");
      out.write("\n");
      out.write("            <script>\n");
      out.write("                function pagarServcicios() {\n");
      out.write("                    if (document.getElementById(\"checkactive\").value < 1) {\n");
      out.write("                        swal(\"No ha seleccionado servicios a pagar.!\", \"Seleccione algún servicio para continuar.\", \"error\").then((value) => {\n");
      out.write("                            window.parent.location.href = '");
      out.print(INICIO);
      out.write("'\n");
      out.write("                        });\n");
      out.write("                        document.getElementById(\"montopagar\").value = \"\";\n");
      out.write("                    } else {\n");
      out.write("                        document.getElementById('btn_submit').hidden = true;\n");
      out.write("                        var total = document.getElementById(\"Total\").value;\n");
      out.write("                        total = total.replace(\".00\", \"\");\n");
      out.write("                        document.getElementById(\"montopagar\").value = total;\n");
      out.write("                        document.pagarServForm.submit();\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            </script>\n");
      out.write("            <div>\n");
      out.write("                <!--<form name=\"pagarServForm\" method=\"POST\" action=\"pagarserviciosQB\">-->\n");
      out.write("                <form name=\"pagarServForm\" method=\"POST\" action=\"pagarserviciosEVO\">\n");
      out.write("\n");
      out.write("                    <input id=\"nispagar\" name=\"nispagar\" hidden  >\n");
      out.write("                    <input id=\"nispagardt\" name=\"nispagardt\"  hidden >\n");
      out.write("                    <input id=\"montopagar\" name=\"montopagar\" hidden >\n");
      out.write("                    <input  name=\"emailpago\" value=\"");
      out.print(usuario);
      out.write("\" hidden >\n");
      out.write("                    <input  name=\"token\" value=\"");
      out.print(token);
      out.write("\" hidden >\n");
      out.write("                    <input id=\"checkactive\"  hidden>\n");
      out.write("\n");
      out.write("\n");
      out.write("                </form>\n");
      out.write("            </div></div>\n");
      out.write("            ");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"footer-section\" style=\"position:relative;bottom:0px;left: 0px;right: 0px;\">\n");
      out.write("    <div class=\"content-wrapper w-container\">\n");
      out.write("        <div class=\"flex-wrapper footer-vertical\">\n");
      out.write("            <a onclick=\"inicioref()\" data-ix=\"fade-out-on-click\" class=\"logo-footer bottom-border w-inline-block\">\n");
      out.write("                \n");
      out.write("                <img src=\"https://uploads-ssl.webflow.com/5ad759a356a64144486fd75f/5afaf23c5d83d94eb98cd446_AYD_Logo_Blanco.png\" srcset=\"https://uploads-ssl.webflow.com/5ad759a356a64144486fd75f/5afaf23c5d83d94eb98cd446_AYD_Logo_Blanco-p-500.png 500w, https://uploads-ssl.webflow.com/5ad759a356a64144486fd75f/5afaf23c5d83d94eb98cd446_AYD_Logo_Blanco-p-800.png 800w, https://uploads-ssl.webflow.com/5ad759a356a64144486fd75f/5afaf23c5d83d94eb98cd446_AYD_Logo_Blanco.png 805w\" sizes=\"188px\" width=\"188\"></a><div class=\"menu-horizontal bottom-border\">\n");
      out.write("                    <a style=\"color: yellow;\" onclick=\"inicioref()\" data-ix=\"fade-out-on-click\" class=\"footer-link horizontal w--current\">\n");
      out.write("                    <script>\n");
      out.write("                        function inicioref() {\n");
      out.write("                            top.location.href = \"https://web.sadm.gob.mx/\";\n");
      out.write("                        }\n");
      out.write("                    </script>\n");
      out.write("                    Inicio\n");
      out.write("                </a>\n");
      out.write("                <a style=\"color: yellow;\" onclick=\"consultaref()\" data-ix=\"fade-out-on-click\" class=\"footer-link horizontal\">\n");
      out.write("                    <script>\n");
      out.write("                        function consultaref() {\n");
      out.write("                            top.location.href = \"https://ayd.sadm.gob.mx/eAyd/\";\n");
      out.write("                        }\n");
      out.write("                    </script>\n");
      out.write("                    Consulta en Linea\n");
      out.write("                </a>\n");
      out.write("                <a style=\"color: yellow;\" onclick=\"consultaref()\" data-ix=\"fade-out-on-click\" class=\"footer-link horizontal\">\n");
      out.write("                    <script>\n");
      out.write("                        function pagoref() {\n");
      out.write("                            top.location.href = \"https://ayd.sadm.gob.mx/eAyd/\";\n");
      out.write("                        }\n");
      out.write("                    </script>\n");
      out.write("                    Pago en Linea\n");
      out.write("                </a>\n");
      out.write("                <a style=\"color: yellow;\" data-ix=\"fade-out-on-click\" onclick=\"factibilidadesref()\" target=\"_blank\" class=\"footer-link horizontal\">\n");
      out.write("                    <script>\n");
      out.write("                        function factibilidadesref() {\n");
      out.write("                            top.location.href = \"https://ayd.sadm.gob.mx/eClickEnLinea/\";\n");
      out.write("                        }\n");
      out.write("                    </script>  \n");
      out.write("                    Factibilidades\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"footer-social-links\">\n");
      out.write("                <a href=\"https://www.facebook.com/AguayDrenajeMty\"  target=\"_blank\" class=\"footer-social-icon facebook w-inline-block\" style=\"opacity: 1; transform: translateX(0px) translateY(0px) translateZ(0px); transition: opacity 300ms ease 0s, transform 800ms ease 0s;\">\n");
      out.write("                    <img src=\"https://uploads-ssl.webflow.com/5ad759a356a64144486fd75f/5ad759a456a641d1616fd7ad_Face-white.svg\" data-ix=\"display-none\" class=\"display-none\" style=\"opacity: 0; display: none; transition: opacity 200ms ease 0s;\" height=\"13\">\n");
      out.write("                </a>\n");
      out.write("                <a href=\"https://twitter.com/AyD_ParaTi\" target=\"_blank\" class=\"footer-social-icon twitter w-inline-block\" style=\"opacity: 1; transform: translateX(0px) translateY(0px) translateZ(0px); transition: opacity 300ms ease 0s, transform 800ms ease 0s;\">\n");
      out.write("                    <img src=\"https://uploads-ssl.webflow.com/5ad759a356a64144486fd75f/5ad759a456a6410e3b6fd7ce_003-simbolo-de-twitter.svg\" data-ix=\"display-none\" class=\"display-none\" style=\"opacity: 0; display: none;\" height=\"13\">\n");
      out.write("                </a>\n");
      out.write("                <a href=\"https://www.instagram.com/ayd_monterrey/\"  target=\"_blank\" class=\"footer-social-icon instagram w-inline-block\" style=\"opacity: 1; transform: translateX(0px) translateY(0px) translateZ(0px); transition: opacity 300ms ease 0s, transform 800ms ease 0s;\">\n");
      out.write("                    <img src=\"https://uploads-ssl.webflow.com/5ad759a356a64144486fd75f/5ad759a456a641515c6fd7a7_002-logo-de-instagram.svg\" class=\"display-none\" height=\"13\">\n");
      out.write("                </a>\n");
      out.write("                <a href=\"https://www.linkedin.com/company/servicios-de-agua-y-drenaje-de-monterrey-ipd\" target=\"_blank\" class=\"footer-social-icon linkedin w-inline-block\" style=\"opacity: 1; transform: translateX(0px) translateY(0px) translateZ(0px); transition: opacity 300ms ease 0s, transform 800ms ease 0s;\">\n");
      out.write("                    <img src=\"https://uploads-ssl.webflow.com/5ad759a356a64144486fd75f/5ad759a456a64138b06fd7ac_004-logo-linkedin.svg\" class=\"display-none\" height=\"13\">\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"w-embed w-script\">\n");
      out.write("            <!--Start of Tawk.to Script-->\n");
      out.write("            <script type=\"text/javascript\">\n");
      out.write("                var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();\n");
      out.write("                (function () {\n");
      out.write("                    var s1 = document.createElement(\"script\"), s0 = document.getElementsByTagName(\"script\")[0];\n");
      out.write("                    s1.async = true;\n");
      out.write("                    s1.src = 'https://embed.tawk.to/5afc7c11227d3d7edc256245/default';\n");
      out.write("                    s1.charset = 'UTF-8';\n");
      out.write("                    s1.setAttribute('crossorigin', '*');\n");
      out.write("                    s0.parentNode.insertBefore(s1, s0);\n");
      out.write("                })();\n");
      out.write("            </script>\n");
      out.write("            <!--End of Tawk.to Script-->\n");
      out.write("        </div>\n");
      out.write("        <div class=\"footer-notice\">\n");
      out.write("            <div class=\"footer-notice-text\">\n");
      out.write("                <span class=\"text-span\">\n");
      out.write("                    2021 Servicios de Agua y Drenaje de Monterrey I.P.D\n");
      out.write("                </span>&nbsp;| &nbsp;\n");
      out.write("                <a onclick=\"terminosref()\" class=\"footer-notice-link\">\n");
      out.write("                    <script>\n");
      out.write("                        function terminosref() {\n");
      out.write("                            top.location.href = \"https://web.sadm.gob.mx/utilerias/terminos-es\";\n");
      out.write("                        }\n");
      out.write("                    </script> \n");
      out.write("                    <span class=\"text-span\">\n");
      out.write("                    Términos y Condiciones\n");
      out.write("                     </span>&nbsp;| &nbsp;\n");
      out.write("                </a>\n");
      out.write("                <a onclick=\"avisoref()\" class=\"footer-notice-link\">\n");
      out.write("                    <script>\n");
      out.write("                        function avisoref() {\n");
      out.write("                            top.location.href = \"https://web.sadm.gob.mx/utilerias/privacidad-es\";\n");
      out.write("                        }\n");
      out.write("                    </script>\n");
      out.write("                    <span class=\"text-span\">\n");
      out.write("                    Avisos de Privacidad\n");
      out.write("                    </span>\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>\n");
}
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
