/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2021-09-07 16:12:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/Bottom.jsp", Long.valueOf(1630099370741L));
    _jspx_dependants.put("/Top.jsp", Long.valueOf(1630099373576L));
    _jspx_dependants.put("/HeaderOptions.jsp", Long.valueOf(1630099372078L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        ");
      out.write("<link href=\"imagenes/logo_transp.gif\" rel=\"shortcut icon\" type=\"image/x-icon\" />\n");
      out.write("<link href=\"imagenes/logo_transp.gif\" rel=\"apple-touch-icon\" />\n");
      out.write("<link href=\"styles/normalize.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<link href=\"styles/main.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<link href=\"styles/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700\" rel=\"stylesheet\"> \n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery3.js\"></script>\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("<link href=\"styles/webflow1.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<link href=\"styles/webflow4.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<link href=\"styles/webflow3.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<script language=\"JavaScript\" src=\"js/script.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script>\n");
      out.write("<!-- CSS only -->\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x\" crossorigin=\"anonymous\">\n");
      out.write("<!-- JavaScript Bundle with Popper -->\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script language=\"JavaScript\" src=\"js/script.js\"></script>\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.min.js\" type=\"text/javascript\" integrity=\"sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://uploads-ssl.webflow.com/5ad759a356a64144486fd75f/js/webflow.d69d0ec41.js\" type=\"text/javascript\"></script>\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.11.2/jquery-ui.js\"></script>");
      out.write("\n");
      out.write("        <title>Pago de Servicios en L&iacute;nea (Login)</title>\n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("    <center>\n");
      out.write("        <script language=\"Javascript\">\n");
      out.write("\n");
      out.write("            function validateForm() {\n");
      out.write("                if (document.loginForm.email.value !== \"\") {\n");
      out.write("\n");
      out.write("                    if (document.loginForm.password.value !== \"\") {\n");
      out.write("                        expr = /^([a-zA-Z0-9_\\.\\-])+\\@(([a-zA-Z0-9\\-])+\\.)+([a-zA-Z0-9]{2,4})+$/;\n");
      out.write("                        if (!expr.test(document.loginForm.email.value)) {\n");
      out.write("                            swal(\"Email es inválido!\", \"Error: La dirección de correo : \" + document.loginForm.email.value + \" : no es válido.\", \"error\").then((value) => {\n");
      out.write("                                window.parent.location.href = 'https://ayd.sadm.gob.mx/eAyd/'\n");
      out.write("                            });\n");
      out.write("\n");
      out.write("\n");
      out.write("                            document.loginForm.email.value = \"\";\n");
      out.write("\n");
      out.write("                        } else {\n");
      out.write("                            document.loginForm.submit();\n");
      out.write("                        }\n");
      out.write("\n");
      out.write("                    } else {\n");
      out.write("                        swal(\"Password es inválido!\", \"Por favor inserte el password.\", \"error\").then((value) => {\n");
      out.write("                            window.parent.location.href = 'https://ayd.sadm.gob.mx/eAyd/'\n");
      out.write("                        });\n");
      out.write("\n");
      out.write("                        document.loginForm.password.focus();\n");
      out.write("                    }\n");
      out.write("                } else {\n");
      out.write("                    swal(\"Email es inválido!\", \"Por favor inserte el email.\", \"error\").then((value) => {\n");
      out.write("                        window.parent.location.href = 'https://ayd.sadm.gob.mx/eAyd/'\n");
      out.write("                    });\n");
      out.write("                    document.loginForm.email.focus();\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        </script>\n");
      out.write("        <style>\n");
      out.write("            a {\n");
      out.write("                text-decoration: none !important;\n");
      out.write("            }\n");
      out.write("            a:hover {\n");
      out.write("                color: #0056b3;\n");
      out.write("                text-decoration: none !important;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("        ");
      out.write("<style>\n");
      out.write("    a{\n");
      out.write("        text-decoration: none !important;\n");
      out.write("    }\n");
      out.write("    a:hover{\n");
      out.write("        text-decoration: none !important;\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("<script>\n");
      out.write("var lastScrollTop = 0;\n");
      out.write("$(window).scroll(function(event){\n");
      out.write("   var st = $(this).scrollTop();\n");
      out.write("   if (st > lastScrollTop){\n");
      out.write("       // downscroll code\n");
      out.write("       document.getElementById(\"TopMenu\").style.display = \"none\"\n");
      out.write("   } else {\n");
      out.write("      // upscroll code\n");
      out.write("      document.getElementById(\"TopMenu\").style.display = \"inline\"\n");
      out.write("   }\n");
      out.write("   lastScrollTop = st;\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<div  data-ix=\"move-down-on-load\" id=\"TopMenu\" data-w-id=\"151ec016-beb1-b657-3bb7-0a531105cafe\" class=\"top-bar\" style=\"opacity: 1; transform: translateX(0px) translateY(0%) translateZ(0px); transition: opacity 200ms ease 0s, transform 800ms ease 0s;\">\n");
      out.write("    <div data-collapse=\"medium\" data-animation=\"default\" data-duration=\"400\" id=\"Top\" class=\"navbar-1 w-nav\">\n");
      out.write("        <div class=\"content-wrapper w-container\">\n");
      out.write("            <script>\n");
      out.write("                function logoref() {\n");
      out.write("                    top.location.href = \"https://web.sadm.gob.mx/\";\n");
      out.write("                }\n");
      out.write("            </script>\n");
      out.write("            <a onclick=\"logoref()\" data-ix=\"fade-out-on-click\" class=\"brand w-nav-brand w--current\">\n");
      out.write("                <img src=\"images/AYD.png\" srcset=\"https://uploads-ssl.webflow.com/5ad759a356a64144486fd75f/5b6b5f504c3819038b156e33_logo%20sadm-p-500.png 500w, https://uploads-ssl.webflow.com/5ad759a356a64144486fd75f/5b6b5f504c3819038b156e33_logo%20sadm-p-800.png 800w, https://uploads-ssl.webflow.com/5ad759a356a64144486fd75f/5b6b5f504c3819038b156e33_logo%20sadm-p-1080.png 1080w, https://uploads-ssl.webflow.com/5ad759a356a64144486fd75f/5b6b5f504c3819038b156e33_logo%20sadm.png 1217w\" sizes=\"(max-width: 479px) 79vw, (max-width: 767px) 192px, 202px\">\n");
      out.write("            </a>\n");
      out.write("            <nav role=\"navigation\" class=\"w-nav-menu\">\n");
      out.write("                <a id=\"inicio\" onclick=\"inicioref()\" data-ix=\"fade-out-on-click\" class=\"navlink w-nav-link\" style=\"max-width: 1170px;\">\n");
      out.write("                    <script>\n");
      out.write("                        function inicioref() {\n");
      out.write("                            top.location.href = \"https://web.sadm.gob.mx/\";\n");
      out.write("                        }\n");
      out.write("                    </script>\n");
      out.write("                    Inicio\n");
      out.write("                </a>\n");
      out.write("                <a id=\"consulta-en-linea\" onclick=\"consultaref()\"  data-ix=\"fade-out-on-click\" class=\"navlink w-nav-link\" style=\"max-width: 1170px;\">\n");
      out.write("                    <script>\n");
      out.write("                        function consultaref() {\n");
      out.write("                            top.location.href = \"https://ayd.sadm.gob.mx/eAyd/\";\n");
      out.write("                        }\n");
      out.write("                    </script>\n");
      out.write("                    Consulta en Línea\n");
      out.write("                </a>                        \n");
      out.write("                <a id=\"pago-en-linea\" onclick=\"pagoref()\" data-ix=\"fade-out-on-click\" class=\"navlink w-nav-link\" style=\"max-width: 1170px;\">\n");
      out.write("                    <script>\n");
      out.write("                        function pagoref() {\n");
      out.write("                            top.location.href = \"https://ayd.sadm.gob.mx/eAyd/\";\n");
      out.write("                        }\n");
      out.write("                    </script>\n");
      out.write("                    Pago en Línea\n");
      out.write("                </a>\n");
      out.write("                <a id=\"factibilidades\" onclick=\"factibilidadesref()\" data-ix=\"fade-out-on-click\" class=\"navlink w-nav-link\" style=\"max-width: 1170px;\">\n");
      out.write("                    <script>\n");
      out.write("                        function factibilidadesref() {\n");
      out.write("                            top.location.href = \"https://ayd.sadm.gob.mx/eClickEnLinea/\";\n");
      out.write("                        }\n");
      out.write("                    </script>\n");
      out.write("                    Factibilidades\n");
      out.write("                </a>      \n");
      out.write("\n");
      out.write("            </nav>\n");
      out.write("            <div class=\"menu-button w-nav-button\">\n");
      out.write("                <div>\n");
      out.write("                    <div class=\"line-1\"></div>\n");
      out.write("                    <div class=\"line-2\"></div>\n");
      out.write("                    <div class=\"line-3\"></div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <div class=\"w-nav-overlay\" data-wf-ignore=\"\"></div>\n");
      out.write("    </div>\n");
      out.write("<br></div>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <div id=\"content\" style=\"width: 80%\">\n");
      out.write("            <div class=\"container-fluid my-4\" \">\n");
      out.write("                <div   class=\"row py-2\"\">\n");
      out.write("                    <div class=\"container py-2\" >\n");
      out.write("                        <!--                        <div hidden class=\"login-container col-12 col-lg-10 float-centre py-4\" style=\"margin-left: 5%;\">\n");
      out.write("                                                    <h2 class=\"text-center mt-1 mb-3\">Disculpe las molestias, por el momento no le podemos atender en este medio.</h2>\n");
      out.write("                                                    <h3 class=\"text-center mt-1 mb-3\">Lo invitamos a ingresar a través de nuestra APP.</h3> \n");
      out.write("                                                    <label>Encuentranos como AYD en Google Play y App Store.</label>\n");
      out.write("                                                    <br>\n");
      out.write("                                                    <img src=\"imagenes/AyDqr.png\" onclick=\"window.parent.location.href = 'https://www.sadm.gob.mx/SADM/qr.html';\" style=\"width: 50%;margin: 5px;\"/>\n");
      out.write("                                                    <br>\n");
      out.write("                                                </div>-->\n");
      out.write("                        <div style=\"text-align: left;\" class=\"login-container col-12 col-lg-5 float-left py-4\">\n");
      out.write("                            <form name=\"loginForm\" method=\"POST\" action=\"autenticacione\">\n");
      out.write("\n");
      out.write("                                <input hidden  name=\"command\" value=\"\">   \n");
      out.write("\n");
      out.write("                                <h3 class=\"text-center mt-1 mb-3\">Ingreso a Servicio en Línea</h3>\n");
      out.write("                                <label for=\"email\">E-Mail:</label>\n");
      out.write("                                <input type=\"text\" name=\"email\" size=\"30\" class=\"form-control\" value=\"\"><br>\n");
      out.write("\n");
      out.write("                                <label for=\"password\">Contraseña:</label>\n");
      out.write("                                <input type=\"password\" name=\"password\" size=\"30\" class=\"form-control\" value=\"\"><br>\n");
      out.write("\n");
      out.write("                                <label>&nbsp;</label>\n");
      out.write("                                <input   type=\"button\" value=\"Continuar\" onClick=\"validateForm();\" class=\"btn btn-outline-secondary\"><br>\n");
      out.write("\n");
      out.write("                                <hr>\n");
      out.write("                            </form>\n");
      out.write("                            <div class=\"text-right\">\n");
      out.write("                                <a href=\"GetPassword.jsp\"><font class=\"pass\"><b>¿Olvidó su password?</b></font></a><br>\n");
      out.write("                                <a href=\"UserRegistration.jsp\"><font class=\"pass\"><b>No estoy Registrado</b></font></a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                        <div  id=\"no-registrado\" class=\" col-12 offset-lg-1 col-lg-6 float-left py-4\">\n");
      out.write("\n");
      out.write("                            <div class=\"row text-center\"><h3 class=\"text-center mt-1 mb-3  pl-3 pr-3 mx-auto pb-2\">No estoy Registrado.</h3></div>\n");
      out.write("                            <div class=\"mt-3\">\n");
      out.write("                                <p>Con el Servicio en Línea de Servicios de Agua y Drenaje de Monterrey podrás obtener:<br></p>\n");
      out.write("                                <ul>\n");
      out.write("                                    <li>Descarga de Facturas Electronicas de tus servicos</li>\n");
      out.write("                                    <!--<li>Envío de Facturas Electronicas por EMail</li>\n");
      out.write("                                    <li>Te notificamos si hay alguna falta de Suministro de Agua</li>\n");
      out.write("                                    <li>Recordatorios de Pagos</li>\n");
      out.write("                                    <li>Te avisamos cuando se haya generado una orden de corte o reducción</li>\n");
      out.write("                                    <li>Además, podrás decidir si deseas que no te llegue tu Factura a Domicilio.</li>-->\n");
      out.write("                                </ul>\n");
      out.write("                                <br>\n");
      out.write("                                 \n");
      out.write("\n");
      out.write("                                    <a  href=\"UserRegistration.jsp?userEmail=1\" class=\"btn btn-outline-secondary\" >Regístrate aquí</a>\n");
      out.write("                                   <br>\n");
      out.write("                                   \n");
      out.write("                                <div class=\"text-center\">\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                         <div   class=\" col-12 offset-lg-1 col-lg-6 float-left py-4\" style=\"margin-left: 5%;\">\n");
      out.write("                                        \n");
      out.write("                                         <label>Encuentranos como AYD en Google Play y App Store.</label>\n");
      out.write("                                        <br>\n");
      out.write("                                        <img src=\"imagenes/AyDqr.png\" onclick=\"window.parent.location.href = 'https://www.sadm.gob.mx/SADM/qr.html';\" style=\"width: 50%;margin: 5px;\"/>\n");
      out.write("                                        <br>\n");
      out.write("                                    </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"container-fluid\">\n");
      out.write("                <div class=\"container text-center\">\n");
      out.write("                    <img class=\"img-fluid\" src=\"images/veri_sign.gif\" style=\"max-width: 300px;\">\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"footer-section\" style=\"position:relative;bottom:0px;left: 0px;right: 0px;\">\n");
      out.write("    <div class=\"content-wrapper w-container\">\n");
      out.write("        <div class=\"flex-wrapper footer-vertical\">\n");
      out.write("            <a onclick=\"inicioref()\" data-ix=\"fade-out-on-click\" class=\"logo-footer bottom-border w-inline-block\">\n");
      out.write("                \n");
      out.write("                <img src=\"https://uploads-ssl.webflow.com/5ad759a356a64144486fd75f/5afaf23c5d83d94eb98cd446_AYD_Logo_Blanco.png\" srcset=\"https://uploads-ssl.webflow.com/5ad759a356a64144486fd75f/5afaf23c5d83d94eb98cd446_AYD_Logo_Blanco-p-500.png 500w, https://uploads-ssl.webflow.com/5ad759a356a64144486fd75f/5afaf23c5d83d94eb98cd446_AYD_Logo_Blanco-p-800.png 800w, https://uploads-ssl.webflow.com/5ad759a356a64144486fd75f/5afaf23c5d83d94eb98cd446_AYD_Logo_Blanco.png 805w\" sizes=\"188px\" width=\"188\"></a><div class=\"menu-horizontal bottom-border\">\n");
      out.write("                    <a style=\"color: yellow;\" onclick=\"inicioref()\" data-ix=\"fade-out-on-click\" class=\"footer-link horizontal w--current\">\n");
      out.write("                    <script>\n");
      out.write("                        function inicioref() {\n");
      out.write("                            top.location.href = \"https://web.sadm.gob.mx/\";\n");
      out.write("                        }\n");
      out.write("                    </script>\n");
      out.write("                    Inicio\n");
      out.write("                </a>\n");
      out.write("                <a style=\"color: yellow;\" onclick=\"consultaref()\" data-ix=\"fade-out-on-click\" class=\"footer-link horizontal\">\n");
      out.write("                    <script>\n");
      out.write("                        function consultaref() {\n");
      out.write("                            top.location.href = \"https://ayd.sadm.gob.mx/eAyd/\";\n");
      out.write("                        }\n");
      out.write("                    </script>\n");
      out.write("                    Consulta en Linea\n");
      out.write("                </a>\n");
      out.write("                <a style=\"color: yellow;\" onclick=\"consultaref()\" data-ix=\"fade-out-on-click\" class=\"footer-link horizontal\">\n");
      out.write("                    <script>\n");
      out.write("                        function pagoref() {\n");
      out.write("                            top.location.href = \"https://ayd.sadm.gob.mx/eAyd/\";\n");
      out.write("                        }\n");
      out.write("                    </script>\n");
      out.write("                    Pago en Linea\n");
      out.write("                </a>\n");
      out.write("                <a style=\"color: yellow;\" data-ix=\"fade-out-on-click\" onclick=\"factibilidadesref()\" target=\"_blank\" class=\"footer-link horizontal\">\n");
      out.write("                    <script>\n");
      out.write("                        function factibilidadesref() {\n");
      out.write("                            top.location.href = \"https://ayd.sadm.gob.mx/eClickEnLinea/\";\n");
      out.write("                        }\n");
      out.write("                    </script>  \n");
      out.write("                    Factibilidades\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"footer-social-links\">\n");
      out.write("                <a href=\"https://www.facebook.com/AguayDrenajeMty\"  target=\"_blank\" class=\"footer-social-icon facebook w-inline-block\" style=\"opacity: 1; transform: translateX(0px) translateY(0px) translateZ(0px); transition: opacity 300ms ease 0s, transform 800ms ease 0s;\">\n");
      out.write("                    <img src=\"https://uploads-ssl.webflow.com/5ad759a356a64144486fd75f/5ad759a456a641d1616fd7ad_Face-white.svg\" data-ix=\"display-none\" class=\"display-none\" style=\"opacity: 0; display: none; transition: opacity 200ms ease 0s;\" height=\"13\">\n");
      out.write("                </a>\n");
      out.write("                <a href=\"https://twitter.com/AyD_ParaTi\" target=\"_blank\" class=\"footer-social-icon twitter w-inline-block\" style=\"opacity: 1; transform: translateX(0px) translateY(0px) translateZ(0px); transition: opacity 300ms ease 0s, transform 800ms ease 0s;\">\n");
      out.write("                    <img src=\"https://uploads-ssl.webflow.com/5ad759a356a64144486fd75f/5ad759a456a6410e3b6fd7ce_003-simbolo-de-twitter.svg\" data-ix=\"display-none\" class=\"display-none\" style=\"opacity: 0; display: none;\" height=\"13\">\n");
      out.write("                </a>\n");
      out.write("                <a href=\"https://www.instagram.com/ayd_monterrey/\"  target=\"_blank\" class=\"footer-social-icon instagram w-inline-block\" style=\"opacity: 1; transform: translateX(0px) translateY(0px) translateZ(0px); transition: opacity 300ms ease 0s, transform 800ms ease 0s;\">\n");
      out.write("                    <img src=\"https://uploads-ssl.webflow.com/5ad759a356a64144486fd75f/5ad759a456a641515c6fd7a7_002-logo-de-instagram.svg\" class=\"display-none\" height=\"13\">\n");
      out.write("                </a>\n");
      out.write("                <a href=\"https://www.linkedin.com/company/servicios-de-agua-y-drenaje-de-monterrey-ipd\" target=\"_blank\" class=\"footer-social-icon linkedin w-inline-block\" style=\"opacity: 1; transform: translateX(0px) translateY(0px) translateZ(0px); transition: opacity 300ms ease 0s, transform 800ms ease 0s;\">\n");
      out.write("                    <img src=\"https://uploads-ssl.webflow.com/5ad759a356a64144486fd75f/5ad759a456a64138b06fd7ac_004-logo-linkedin.svg\" class=\"display-none\" height=\"13\">\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"w-embed w-script\">\n");
      out.write("            <!--Start of Tawk.to Script-->\n");
      out.write("            <script type=\"text/javascript\">\n");
      out.write("                var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();\n");
      out.write("                (function () {\n");
      out.write("                    var s1 = document.createElement(\"script\"), s0 = document.getElementsByTagName(\"script\")[0];\n");
      out.write("                    s1.async = true;\n");
      out.write("                    s1.src = 'https://embed.tawk.to/5afc7c11227d3d7edc256245/default';\n");
      out.write("                    s1.charset = 'UTF-8';\n");
      out.write("                    s1.setAttribute('crossorigin', '*');\n");
      out.write("                    s0.parentNode.insertBefore(s1, s0);\n");
      out.write("                })();\n");
      out.write("            </script>\n");
      out.write("            <!--End of Tawk.to Script-->\n");
      out.write("        </div>\n");
      out.write("        <div class=\"footer-notice\">\n");
      out.write("            <div class=\"footer-notice-text\">\n");
      out.write("                <span class=\"text-span\">\n");
      out.write("                    2021 Servicios de Agua y Drenaje de Monterrey I.P.D\n");
      out.write("                </span>&nbsp;| &nbsp;\n");
      out.write("                <a onclick=\"terminosref()\" class=\"footer-notice-link\">\n");
      out.write("                    <script>\n");
      out.write("                        function terminosref() {\n");
      out.write("                            top.location.href = \"https://web.sadm.gob.mx/utilerias/terminos-es\";\n");
      out.write("                        }\n");
      out.write("                    </script> \n");
      out.write("                    <span class=\"text-span\">\n");
      out.write("                    Términos y Condiciones\n");
      out.write("                     </span>&nbsp;| &nbsp;\n");
      out.write("                </a>\n");
      out.write("                <a onclick=\"avisoref()\" class=\"footer-notice-link\">\n");
      out.write("                    <script>\n");
      out.write("                        function avisoref() {\n");
      out.write("                            top.location.href = \"https://web.sadm.gob.mx/utilerias/privacidad-es\";\n");
      out.write("                        }\n");
      out.write("                    </script>\n");
      out.write("                    <span class=\"text-span\">\n");
      out.write("                    Avisos de Privacidad\n");
      out.write("                    </span>\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("    </center>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
