/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2021-09-09 21:01:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class LoginFrame_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/HeaderOptions.jsp", Long.valueOf(1630099372078L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\n");
      out.write("    \"https://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <link href=\"imagenes/logo_transp.gif\" rel=\"shortcut icon\" type=\"image/x-icon\" />\n");
      out.write("        <link href=\"imagenes/logo_transp.gif\" rel=\"apple-touch-icon\" />\n");
      out.write("        \n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("        ");
      out.write("<link href=\"imagenes/logo_transp.gif\" rel=\"shortcut icon\" type=\"image/x-icon\" />\n");
      out.write("<link href=\"imagenes/logo_transp.gif\" rel=\"apple-touch-icon\" />\n");
      out.write("<link href=\"styles/normalize.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<link href=\"styles/main.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<link href=\"styles/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700\" rel=\"stylesheet\"> \n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery3.js\"></script>\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("<link href=\"styles/webflow1.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<link href=\"styles/webflow4.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<link href=\"styles/webflow3.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<script language=\"JavaScript\" src=\"js/script.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script>\n");
      out.write("<!-- CSS only -->\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x\" crossorigin=\"anonymous\">\n");
      out.write("<!-- JavaScript Bundle with Popper -->\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script language=\"JavaScript\" src=\"js/script.js\"></script>\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.min.js\" type=\"text/javascript\" integrity=\"sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://uploads-ssl.webflow.com/5ad759a356a64144486fd75f/js/webflow.d69d0ec41.js\" type=\"text/javascript\"></script>\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.11.2/jquery-ui.js\"></script>");
      out.write("\n");
      out.write("        <title>Pago de Servicios en L&iacute;nea (Login)</title>\n");
      out.write("        <script src=\"https://ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js\" type=\"text/javascript\"></script>\n");
      out.write("        <link href=\"styles/webflow1.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <link href=\"styles/webflow4.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <link href=\"styles/webflow3.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        \n");
      out.write("        <script language=\"Javascript\">\n");
      out.write("            \n");
      out.write("    function validateForm() {\n");
      out.write("        if (document.loginFormFrame.email.value !== \"\") {\n");
      out.write("         \n");
      out.write("            if (document.loginFormFrame.password.value !== \"\") {\n");
      out.write("                expr = /^([a-zA-Z0-9_\\.\\-])+\\@(([a-zA-Z0-9\\-])+\\.)+([a-zA-Z0-9]{2,4})+$/;\n");
      out.write("                                    if (!expr.test(document.loginFormFrame.email.value)){\n");
      out.write("                                        swal(\"Error: La dirección de correo ::: \" + document.loginFormFrame.email.value + \" ::: no es válido.\");\n");
      out.write("                                    document.loginFormFrame.email.value = \"\";\n");
      out.write("                                \n");
      out.write("                                }else{document.loginFormFrame.submit();}\n");
      out.write("                \n");
      out.write("            } else {\n");
      out.write("                swal(\"Por favor inserte el password.\");\n");
      out.write("                document.loginFormFrame.password.focus();\n");
      out.write("            }\n");
      out.write("        } else {\n");
      out.write("            swal(\"Por favor inserte el email.\");\n");
      out.write("            document.loginFormFrame.email.focus();\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\n");
      out.write(" \n");
      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("\n");
      out.write("        </script>\n");
      out.write("    \n");
      out.write("    </head>\n");
      out.write("    <body >\n");
      out.write("        <!-- HEADER -->\n");
      out.write("        \n");
      out.write("        <div style=\"vertical-align: top;position:absolute; top:0; left:0;\" class=\"login-container col-lg-5 float-left py-4\">\n");
      out.write("                        <form name=\"loginFormFrame\" method=\"POST\" action=\"autframe\">\n");
      out.write(" \n");
      out.write("\n");
      out.write("                            <h2 class=\"text-center mt-1 mb-3\"><strong>Ingreso a Servicio en Línea</strong></h2>\n");
      out.write("                            <label for=\"email\">E-Mail:\n");
      out.write("                            <input type=\"text\" name=\"email\" size=\"30\" class=\"form-control\"  value=\"\"></label>\n");
      out.write("                         \n");
      out.write("                            <label for=\"password\">Contraseña:\n");
      out.write("                            <input type=\"password\" name=\"password\" size=\"30\" class=\"form-control\"  value=\"\"></label>\n");
      out.write("                            \n");
      out.write("                            <input  type=\"button\" value=\"Continuar\" onclick=\"validateForm();\" class=\"btn btn-outline-secondary\"><br>\n");
      out.write("\n");
      out.write("                            \n");
      out.write("                       </form>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("      \n");
      out.write("   \n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
